# Groups I-L (France, Senegal, Iraq, Norway,
#             Argentina, Algeria, Austria, Jordan,
#             Portugal, DR Congo, Uzbekistan, Colombia,
#             England, Croatia, Ghana, Panama)

squads_part3 = {

    # ── GROUP I ──────────────────────────────────────────────────────────────

    'fra': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'מייק מינייאן',         'number': 1,  'position': 'GK',  'club': 'מנצ׳סטר סיטי'},
            {'name': 'בנז׳מן פאבר',          'number': 2,  'position': 'DEF', 'club': 'בארסלונה'},
            {'name': 'ד׳יאיי אופנדה',        'number': 5,  'position': 'DEF', 'club': 'PSG'},
            {'name': 'לוקאס הרנאנדס',        'number': 22, 'position': 'DEF', 'club': 'PSG'},
            {'name': 'תיאו הרנאנדס',         'number': 21, 'position': 'DEF', 'club': 'AC מילאן'},
            {'name': 'אדריאן ראביו',          'number': 14, 'position': 'MID', 'club': 'מרסיי'},
            {'name': 'אורליאן צ׳וואמני',     'number': 8,  'position': 'MID', 'club': 'ריאל מדריד'},
            {'name': 'ורן טולסו',             'number': 6,  'position': 'MID', 'club': 'לאציו'},
            {'name': 'אוסמן דמבלה',          'number': 11, 'position': 'FWD', 'club': 'PSG'},
            {'name': 'קיליאן מבאפה',         'number': 10, 'position': 'FWD', 'club': 'ריאל מדריד'},
            {'name': 'מרקוס תורם',            'number': 9,  'position': 'FWD', 'club': 'אינטר'},
        ],
        'bench': [
            {'name': 'אלפונס ארולה',          'number': 23, 'position': 'GK',  'club': 'PSG'},
            {'name': 'ז׳ול קונדה',            'number': 4,  'position': 'DEF', 'club': 'בארסלונה'},
            {'name': 'מתיאס תורם',            'number': 7,  'position': 'FWD', 'club': 'אינטר'},
            {'name': 'ז׳ן-פיליפ מאטטה',     'number': 13, 'position': 'MID', 'club': 'ריאל מדריד'},
            {'name': 'ראנדל קולו מואני',      'number': 19, 'position': 'FWD', 'club': 'יובנטוס'},
        ],
    },

    'sen': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'עדוארד מנדי',          'number': 1,  'position': 'GK',  'club': 'אל-אהלי'},
            {'name': 'יוסוף סאבאלי',         'number': 2,  'position': 'DEF', 'club': 'ברייטון'},
            {'name': 'קאלידו קולייבלי',      'number': 3,  'position': 'DEF', 'club': 'אל-הילאל'},
            {'name': 'אבדו דיאלו',            'number': 5,  'position': 'DEF', 'club': 'אטלנטה'},
            {'name': 'פאלו גאיה',             'number': 22, 'position': 'DEF', 'club': 'ניוקאסל'},
            {'name': 'קוגן בלד',              'number': 6,  'position': 'MID', 'club': 'ריים'},
            {'name': 'שיירו פאל',             'number': 8,  'position': 'MID', 'club': 'אינטר'},
            {'name': 'נמנג׳ה מנדי',           'number': 7,  'position': 'MID', 'club': 'הפרנקפורט'},
            {'name': 'בולאיה דיא',            'number': 11, 'position': 'FWD', 'club': 'ויאריאל'},
            {'name': 'סאדיו מאנה',            'number': 10, 'position': 'FWD', 'club': 'אל-נסר'},
            {'name': 'איסמאילה סאר',          'number': 23, 'position': 'FWD', 'club': 'ווסטהאם'},
        ],
        'bench': [
            {'name': 'אלפה סי',               'number': 16, 'position': 'GK',  'club': 'ניס'},
            {'name': 'נובי מנדס',             'number': 4,  'position': 'DEF', 'club': 'PSG'},
            {'name': 'לנין צ׳אלובה',          'number': 14, 'position': 'MID', 'club': 'לאציו'},
            {'name': 'נדאיה גואיה',           'number': 9,  'position': 'FWD', 'club': 'לה האבר'},
            {'name': 'ניקולאס ג׳קסון',        'number': 17, 'position': 'FWD', 'club': 'צ׳לסי'},
        ],
    },

    'irq': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'ג׳אליל חנטוש',         'number': 1,  'position': 'GK',  'club': 'זוראן'},
            {'name': 'מוחמד חמיד',            'number': 2,  'position': 'DEF', 'club': 'אל-קווה אל-ג׳ויה'},
            {'name': 'עלי ג׳בר',              'number': 5,  'position': 'DEF', 'club': 'אל-שורטה'},
            {'name': 'עומר עבד-אלרחמן',       'number': 6,  'position': 'DEF', 'club': 'אל-ג׳יש'},
            {'name': 'ד׳רגהאם אסמאעיל',       'number': 3,  'position': 'DEF', 'club': 'אל-קווה אל-ג׳ויה'},
            {'name': 'איבראהים בישר',          'number': 8,  'position': 'MID', 'club': 'זוראן'},
            {'name': 'מוחמד קאסם',            'number': 4,  'position': 'MID', 'club': 'אל-זורה'},
            {'name': 'עאמר עלי',              'number': 7,  'position': 'MID', 'club': 'אל-שורטה'},
            {'name': 'חוסיין עלי',            'number': 11, 'position': 'MID', 'club': 'אל-ג׳יש'},
            {'name': 'עיס אלן עלי',           'number': 10, 'position': 'FWD', 'club': 'זוראן'},
            {'name': 'אחמד יאסין',            'number': 9,  'position': 'FWD', 'club': 'פנרבהצ׳ה'},
        ],
        'bench': [
            {'name': 'חסן ג׳מיל',             'number': 12, 'position': 'GK',  'club': 'אל-שורטה'},
            {'name': 'לית׳ רחמן',             'number': 15, 'position': 'DEF', 'club': 'זוראן'},
            {'name': 'עלי סאלם',              'number': 14, 'position': 'MID', 'club': 'אל-זורה'},
            {'name': 'מוחמד עמאד',            'number': 17, 'position': 'FWD', 'club': 'הגראפה'},
            {'name': 'יוסוף עמאד',            'number': 19, 'position': 'FWD', 'club': 'זוראן'},
        ],
    },

    'nor': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'רונה ג׳רגל',            'number': 1,  'position': 'GK',  'club': 'ברייטון'},
            {'name': 'אנדרס מוברק',           'number': 2,  'position': 'DEF', 'club': 'לידס'},
            {'name': 'סטיאן יהנסן',           'number': 5,  'position': 'DEF', 'club': 'בורוסיה דורטמונד'},
            {'name': 'לאו אוסטיגאד',          'number': 6,  'position': 'DEF', 'club': 'מולדה'},
            {'name': 'בד המר-לנדסוורק',        'number': 3,  'position': 'DEF', 'club': 'בורוסיה דורטמונד'},
            {'name': 'מרטין אודגאר',          'number': 8,  'position': 'MID', 'club': 'ניוקאסל'},
            {'name': 'ססי ניינג',             'number': 4,  'position': 'MID', 'club': 'ניוקאסל'},
            {'name': 'מאגנוס דרגון',          'number': 7,  'position': 'MID', 'club': 'מנצ׳סטר יונייטד'},
            {'name': 'כריסטיאן אוליצ׳',       'number': 11, 'position': 'FWD', 'club': 'פנרבהצ׳ה'},
            {'name': 'ארלינג ה-לאן',          'number': 9,  'position': 'FWD', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'אנטוניו נוסה',          'number': 10, 'position': 'FWD', 'club': 'שאכטר'},
        ],
        'bench': [
            {'name': 'אורגן ספת',              'number': 12, 'position': 'GK',  'club': 'גיון'},
            {'name': 'תורבקטן לוד',           'number': 15, 'position': 'DEF', 'club': 'שלקה'},
            {'name': 'פטריק בורג',             'number': 17, 'position': 'MID', 'club': 'VfB שטוטגרט'},
            {'name': 'יוהאנס הופ',            'number': 14, 'position': 'FWD', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'פרדריק מידציין',         'number': 19, 'position': 'FWD', 'club': 'ניס'},
        ],
    },

    # ── GROUP J ──────────────────────────────────────────────────────────────

    'arg': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'אמיליאנו מרטינס',       'number': 23, 'position': 'GK',  'club': 'אסטון וילה'},
            {'name': 'נאהואל מולינה',          'number': 26, 'position': 'DEF', 'club': 'אטלטיקו מדריד'},
            {'name': 'קריסטיאן רומרו',         'number': 13, 'position': 'DEF', 'club': 'טוטנהם'},
            {'name': 'ליסנדרו מרטינס',         'number': 25, 'position': 'DEF', 'club': 'מנצ׳סטר יונייטד'},
            {'name': 'מרקוס אקוניה',           'number': 8,  'position': 'DEF', 'club': 'ספרטה רוטרדם'},
            {'name': 'אנחל דה מריה',           'number': 11, 'position': 'MID', 'club': 'בנפיקה'},
            {'name': 'רוד׳ריגו דה פול',        'number': 7,  'position': 'MID', 'club': 'אטלטיקו מדריד'},
            {'name': 'אנסו פרנאנדס',           'number': 14, 'position': 'MID', 'club': 'צ׳לסי'},
            {'name': 'אלכסיס מק אליסטר',       'number': 20, 'position': 'MID', 'club': 'ליברפול'},
            {'name': 'ליאונל מסי',             'number': 10, 'position': 'FWD', 'club': 'אינטר מיאמי'},
            {'name': 'חוליאן אלבארס',          'number': 9,  'position': 'FWD', 'club': 'אטלטיקו מדריד'},
        ],
        'bench': [
            {'name': 'חרונימו רוי',            'number': 1,  'position': 'GK',  'club': 'פורטו'},
            {'name': 'ניקולאס אוטמנדי',        'number': 19, 'position': 'DEF', 'club': 'בנפיקה'},
            {'name': 'ניקולס גונסאלס',         'number': 22, 'position': 'FWD', 'club': 'פיורנטינה'},
            {'name': 'לאוטארו מרטינס',         'number': 22, 'position': 'FWD', 'club': 'אינטר'},
            {'name': 'פאולו דיבאלה',           'number': 21, 'position': 'FWD', 'club': 'AS רומא'},
            {'name': 'הוביד אדינגרא',           'number': 17, 'position': 'MID', 'club': 'אטלטיקו'},
        ],
    },

    'alg': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'ריים צ׳בל',              'number': 1,  'position': 'GK',  'club': 'אנג׳ה'},
            {'name': 'אנאס טאהר',              'number': 2,  'position': 'DEF', 'club': 'קלרמון'},
            {'name': 'ז׳יאן-קלוד בילל',        'number': 5,  'position': 'DEF', 'club': 'ניס'},
            {'name': 'אייסה מנדי',             'number': 6,  'position': 'DEF', 'club': 'ליגה דה קיטו'},
            {'name': 'רמי בנסבאיני',           'number': 3,  'position': 'DEF', 'club': 'בורוסיה דורטמונד'},
            {'name': 'נאסר לרבי',              'number': 8,  'position': 'MID', 'club': 'פרנקפורט'},
            {'name': 'הוסם אוארי',             'number': 4,  'position': 'MID', 'club': 'אל-שביב'},
            {'name': 'ריאד מהרז',              'number': 7,  'position': 'MID', 'club': 'אל-אתיחאד'},
            {'name': 'יאסין בנאלי',            'number': 17, 'position': 'FWD', 'club': 'פוג׳יאן'},
            {'name': 'איסלאם סלימאני',         'number': 9,  'position': 'FWD', 'club': 'אל-אתיחאד'},
            {'name': 'בגאי מרח',               'number': 11, 'position': 'FWD', 'club': 'ריאל מדריד'},
        ],
        'bench': [
            {'name': 'ד׳ז׳מל בנת׳ביס',        'number': 16, 'position': 'GK',  'club': 'MC אלג׳יר'},
            {'name': 'ד׳יאיי בנלמחד',          'number': 15, 'position': 'DEF', 'club': 'ויאריאל'},
            {'name': 'בלאל בנהמאמה',           'number': 14, 'position': 'MID', 'club': 'ריים'},
            {'name': 'סופיאן פגולי',           'number': 19, 'position': 'FWD', 'club': 'אל-קדסייה'},
            {'name': 'ד׳יאיי תיאו',            'number': 20, 'position': 'FWD', 'club': 'ES סטיף'},
        ],
    },

    'aut': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'פטריק פנמאן',            'number': 1,  'position': 'GK',  'club': 'פריירה'},
            {'name': 'סטפן לאינר',             'number': 2,  'position': 'DEF', 'club': 'מינכן'},
            {'name': 'דוד אלבה',               'number': 5,  'position': 'DEF', 'club': 'ריאל מדריד'},
            {'name': 'פילמר הינטרגר',          'number': 4,  'position': 'DEF', 'club': 'פרנקפורט'},
            {'name': 'מקסימיליאן ווובר',       'number': 3,  'position': 'DEF', 'club': 'ליברפול'},
            {'name': 'מרקו ארנאוטוביץ׳',       'number': 7,  'position': 'MID', 'club': 'אינטר'},
            {'name': 'קונראד לאימר',           'number': 8,  'position': 'MID', 'club': 'ליברפול'},
            {'name': 'נחאל ב-ריד',             'number': 6,  'position': 'MID', 'club': 'לוהאבר'},
            {'name': 'כריסטוף באומגרטנר',      'number': 14, 'position': 'FWD', 'club': 'לפציג'},
            {'name': 'מיכאל גרגיץ׳',           'number': 9,  'position': 'FWD', 'club': 'שטוטגרט'},
            {'name': 'אלסנדר פינוויל',         'number': 11, 'position': 'FWD', 'club': 'מאינץ'},
        ],
        'bench': [
            {'name': 'אלכסנדר שלאגר',         'number': 12, 'position': 'GK',  'club': 'שטורם גראץ'},
            {'name': 'פיל מנדל',               'number': 15, 'position': 'DEF', 'club': 'שטורם גראץ'},
            {'name': 'פלוריאן קין',            'number': 17, 'position': 'MID', 'club': 'אינטר'},
            {'name': 'מתיאס זייסל',            'number': 10, 'position': 'MID', 'club': 'RC לנס'},
            {'name': 'אנדי ז׳ורנה',            'number': 19, 'position': 'FWD', 'club': 'מנצ׳סטר יונייטד'},
        ],
    },

    'jor': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'יאזאן אבו-עלייאן',       'number': 1,  'position': 'GK',  'club': 'אל-פייסלי'},
            {'name': 'מוחמד אבו-השש',          'number': 2,  'position': 'DEF', 'club': 'אל-ווחדה'},
            {'name': 'בסם חוסין',              'number': 5,  'position': 'DEF', 'club': 'אל-קמאל'},
            {'name': 'עומר ח׳רייש',            'number': 6,  'position': 'DEF', 'club': 'אל-ווחדה'},
            {'name': 'אחמד ד׳מיר',             'number': 3,  'position': 'DEF', 'club': 'אל-פייסלי'},
            {'name': 'עיס אבו-עיישה',         'number': 8,  'position': 'MID', 'club': 'אל-ג׳זירה'},
            {'name': 'בלאל אבו-ז׳ין',          'number': 4,  'position': 'MID', 'club': 'אל-פייסלי'},
            {'name': 'אחמד עאיש',              'number': 7,  'position': 'MID', 'club': 'אל-ווחדה'},
            {'name': 'מוחמד ד׳יאב',            'number': 11, 'position': 'MID', 'club': 'אל-פייסלי'},
            {'name': 'מוסא אל-תעאמרה',         'number': 10, 'position': 'FWD', 'club': 'ניסה'},
            {'name': 'יאזן אל-ד׳הרי',          'number': 9,  'position': 'FWD', 'club': 'לוהאבר'},
        ],
        'bench': [
            {'name': 'עמאד אל-ד׳רזי',         'number': 12, 'position': 'GK',  'club': 'אל-ג׳זירה'},
            {'name': 'נאסר אל-ד׳מיר',         'number': 14, 'position': 'DEF', 'club': 'אל-ווחדה'},
            {'name': 'עמאד בני-עיישה',         'number': 17, 'position': 'MID', 'club': 'אל-פייסלי'},
            {'name': 'ז׳ן מחמד',               'number': 19, 'position': 'FWD', 'club': 'אל-קמאל'},
            {'name': 'מוחמד מוסא',             'number': 20, 'position': 'FWD', 'club': 'אל-ג׳זירה'},
        ],
    },

    # ── GROUP K ──────────────────────────────────────────────────────────────

    'por': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'רוי פאטריסיו',           'number': 1,  'position': 'GK',  'club': 'RC לנס'},
            {'name': 'ז׳ואאו קנסלו',           'number': 20, 'position': 'DEF', 'club': 'בארסלונה'},
            {'name': 'ז׳ואאו פאלייניאה',       'number': 3,  'position': 'DEF', 'club': 'אסטון וילה'},
            {'name': 'ריוארד ורדיסו',          'number': 4,  'position': 'DEF', 'club': 'טוטנהם'},
            {'name': 'נונו מנדס',              'number': 22, 'position': 'DEF', 'club': 'PSG'},
            {'name': 'ז׳ואאו פאליניה',         'number': 16, 'position': 'MID', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'ויטינה',                 'number': 8,  'position': 'MID', 'club': 'PSG'},
            {'name': 'ב׳רנרדו סילבה',          'number': 10, 'position': 'MID', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'ז׳ואאו פליקס',           'number': 11, 'position': 'FWD', 'club': 'בארסלונה'},
            {'name': 'קריסטיאנו רונאלדו',      'number': 7,  'position': 'FWD', 'club': 'אל-נסר'},
            {'name': 'ראפאל לאאו',             'number': 17, 'position': 'FWD', 'club': 'AC מילאן'},
        ],
        'bench': [
            {'name': 'דיוגו קוסטה',            'number': 12, 'position': 'GK',  'club': 'פורטו'},
            {'name': 'אנטוניו סילבה',          'number': 6,  'position': 'DEF', 'club': 'בנפיקה'},
            {'name': 'ברונו פרנאנדס',          'number': 8,  'position': 'MID', 'club': 'מנצ׳סטר יונייטד'},
            {'name': 'גונסאלו ראמוס',           'number': 9,  'position': 'FWD', 'club': 'PSG'},
            {'name': 'פדרו נטו',               'number': 19, 'position': 'FWD', 'club': 'צ׳לסי'},
        ],
    },

    'cod': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'גאווין יאו',              'number': 1,  'position': 'GK',  'club': 'אל-קאהרה'},
            {'name': 'גינאל אנגוסו',           'number': 2,  'position': 'DEF', 'club': 'AS V.Club'},
            {'name': 'ד׳יוגו דאלוט',           'number': 5,  'position': 'DEF', 'club': 'TP מאזמבה'},
            {'name': 'ד׳יאיי מוסנגו',          'number': 6,  'position': 'DEF', 'club': 'אל-אהלי'},
            {'name': 'ז׳אן-ד׳יו כינגו',        'number': 3,  'position': 'DEF', 'club': 'TP מאזמבה'},
            {'name': 'חוסא זינגה',             'number': 8,  'position': 'MID', 'club': 'TP מאזמבה'},
            {'name': 'מוישה מלמבה',            'number': 4,  'position': 'MID', 'club': 'TP מאזמבה'},
            {'name': 'ד׳יאיי לויאמה',          'number': 7,  'position': 'MID', 'club': 'AS V.Club'},
            {'name': 'ד׳יאיי חסמה',            'number': 11, 'position': 'MID', 'club': 'AS V.Club'},
            {'name': 'ד׳ולאנד מוסאנגו',         'number': 10, 'position': 'FWD', 'club': 'TP מאזמבה'},
            {'name': 'ז׳וניאל נגמה',            'number': 9,  'position': 'FWD', 'club': 'Roda JC'},
        ],
        'bench': [
            {'name': 'ד׳יאיי קבוסה',           'number': 16, 'position': 'GK',  'club': 'TP מאזמבה'},
            {'name': 'ד׳יוגו פליפה',           'number': 15, 'position': 'DEF', 'club': 'AS V.Club'},
            {'name': 'ד׳יאיי ד׳ולאנד',         'number': 17, 'position': 'MID', 'club': 'TP מאזמבה'},
            {'name': 'ז׳אן-ז׳ק מונגה',         'number': 19, 'position': 'FWD', 'club': 'DCMP מוישה'},
            {'name': 'ד׳יאיי לומא',            'number': 21, 'position': 'FWD', 'club': 'AS V.Club'},
        ],
    },

    'uzb': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'אולוגבק ניישלטוב',       'number': 1,  'position': 'GK',  'club': 'FC פחטקור'},
            {'name': 'ג׳סור נאסימוב',          'number': 2,  'position': 'DEF', 'club': 'FC לוקומוטיב'},
            {'name': 'חאמזה קאשגרי',            'number': 5,  'position': 'DEF', 'club': 'FC פחטקור'},
            {'name': 'עוטקיר יוסופוב',         'number': 6,  'position': 'DEF', 'club': 'FC נפטצ׳י'},
            {'name': 'חוסן ח׳איטוב',           'number': 3,  'position': 'DEF', 'club': 'FC פחטקור'},
            {'name': 'ג׳משיד איסקנדרוב',       'number': 8,  'position': 'MID', 'club': 'FC פחטקור'},
            {'name': 'עאבדולה אבדוחאלילוב',    'number': 4,  'position': 'MID', 'club': 'FC לוקומוטיב'},
            {'name': 'ח׳ורשיד מוסיימוב',       'number': 7,  'position': 'MID', 'club': 'FC נפטצ׳י'},
            {'name': 'עאבדוקוביר ח׳אסנוב',    'number': 11, 'position': 'MID', 'club': 'FC נשט-25'},
            {'name': 'עלישיר ג׳ינוב',          'number': 10, 'position': 'FWD', 'club': 'ג׳נראה'},
            {'name': 'אבובכר צ׳מנוב',          'number': 9,  'position': 'FWD', 'club': 'נורדסאלנד'},
        ],
        'bench': [
            {'name': 'ד׳ורא קריימוב',          'number': 13, 'position': 'GK',  'club': 'FC לוקומוטיב'},
            {'name': 'בכרומ ביתמוב',           'number': 14, 'position': 'DEF', 'club': 'FC פחטקור'},
            {'name': 'שרוף מוחמדוב',           'number': 17, 'position': 'MID', 'club': 'FC לוקומוטיב'},
            {'name': 'ז׳אספול ביגוב',          'number': 19, 'position': 'FWD', 'club': 'FC נשט-25'},
            {'name': 'ח׳איידר עלייב',          'number': 20, 'position': 'FWD', 'club': 'נורדסאלנד'},
        ],
    },

    'col': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'קאמילו ווארגס',          'number': 1,  'position': 'GK',  'club': 'אטלנטה יונייטד'},
            {'name': 'דניאל מוניוס',           'number': 2,  'position': 'DEF', 'club': 'ווינסנס'},
            {'name': 'דאוינסון סנצ׳ס',        'number': 6,  'position': 'DEF', 'club': 'אסטון וילה'},
            {'name': 'קרלוס צ׳בר',            'number': 4,  'position': 'DEF', 'club': 'ויאריאל'},
            {'name': 'ג׳והאן מוחיקה',          'number': 3,  'position': 'DEF', 'club': 'ריאל סוסיאדד'},
            {'name': 'ג׳פרסון לרמה',           'number': 8,  'position': 'MID', 'club': 'בנפיקה'},
            {'name': 'ריצ׳ארד ריוס',           'number': 16, 'position': 'MID', 'club': 'פרמה'},
            {'name': 'מאטאוס אונה',            'number': 7,  'position': 'MID', 'club': 'אינטר'},
            {'name': 'לואיס דיאס',             'number': 11, 'position': 'FWD', 'club': 'ליברפול'},
            {'name': 'ראדאמל פלקאו',           'number': 9,  'position': 'FWD', 'club': 'AS מונאקו'},
            {'name': 'הואן קוואדראדו',         'number': 10, 'position': 'FWD', 'club': 'אינטר'},
        ],
        'bench': [
            {'name': 'ד׳יויד אוספינה',         'number': 12, 'position': 'GK',  'club': 'אל-קדסייה'},
            {'name': 'יירי מינה',               'number': 13, 'position': 'DEF', 'club': 'פנרבהצ׳ה'},
            {'name': 'ויגנר לאמינה',            'number': 14, 'position': 'MID', 'club': 'פאלמיירס'},
            {'name': 'מיגל אנחל בורחה',        'number': 19, 'position': 'FWD', 'club': 'ריבר פלייט'},
            {'name': 'כרלוס אדוארדו',          'number': 17, 'position': 'FWD', 'club': 'אל-הילאל'},
        ],
    },

    # ── GROUP L ──────────────────────────────────────────────────────────────

    'eng': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'ג׳ורדן פיקפורד',         'number': 1,  'position': 'GK',  'club': 'אוורטון'},
            {'name': 'טרנט אלכסנדר-ארנולד',   'number': 66, 'position': 'DEF', 'club': 'ריאל מדריד'},
            {'name': 'הארי מגווייר',            'number': 6,  'position': 'DEF', 'club': 'מנצ׳סטר יונייטד'},
            {'name': 'מרק גהי',                'number': 5,  'position': 'DEF', 'club': 'בארסלונה'},
            {'name': 'לואיז הול',               'number': 3,  'position': 'DEF', 'club': 'ניוקאסל'},
            {'name': 'ג׳ודי בלינגהם',           'number': 8,  'position': 'MID', 'club': 'ריאל מדריד'},
            {'name': 'דקלאן רייס',              'number': 4,  'position': 'MID', 'club': 'ארסנל'},
            {'name': 'קוביל מיינו',             'number': 7,  'position': 'MID', 'club': 'ארסנל'},
            {'name': 'סאקה',                    'number': 7,  'position': 'FWD', 'club': 'ארסנל'},
            {'name': 'הארי קיין',               'number': 9,  'position': 'FWD', 'club': 'באיירן מינכן'},
            {'name': 'פיל פודן',                'number': 10, 'position': 'FWD', 'club': 'מנצ׳סטר סיטי'},
        ],
        'bench': [
            {'name': 'דיין הנדרסון',            'number': 13, 'position': 'GK',  'club': 'נוטינגהם פורסט'},
            {'name': 'קייל ווקר',               'number': 2,  'position': 'DEF', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'קול פאלמר',               'number': 20, 'position': 'MID', 'club': 'צ׳לסי'},
            {'name': 'אנתוני גורדון',            'number': 11, 'position': 'FWD', 'club': 'ניוקאסל'},
            {'name': 'אולי ווטקינס',             'number': 14, 'position': 'FWD', 'club': 'אסטון וילה'},
        ],
    },

    'cro': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'דומיניק ליוואקוביץ׳',    'number': 1,  'position': 'GK',  'club': 'פנרבהצ׳ה'},
            {'name': 'יוסיפ יורנלוביץ׳',       'number': 2,  'position': 'DEF', 'club': 'בריז׳ה'},
            {'name': 'יוסקו גווארדיול',         'number': 24, 'position': 'DEF', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'דאיו אפאה',               'number': 5,  'position': 'DEF', 'club': 'לפציג'},
            {'name': 'בורנה סוסה',              'number': 3,  'position': 'DEF', 'club': 'טראבזונספור'},
            {'name': 'לוקה מודריץ׳',            'number': 10, 'position': 'MID', 'club': 'ריאל מדריד'},
            {'name': 'מארצ׳לו ברוזוביץ׳',       'number': 11, 'position': 'MID', 'club': 'אל-נסר'},
            {'name': 'מתאו קוביץ׳יץ׳',         'number': 8,  'position': 'MID', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'איוואן פריישיץ׳',         'number': 7,  'position': 'FWD', 'club': 'אטלנטה'},
            {'name': 'אנדריי קראמריץ׳',         'number': 9,  'position': 'FWD', 'club': 'הופנהיים'},
            {'name': 'ברונו פטקוביץ׳',          'number': 17, 'position': 'FWD', 'club': 'גרנד'},
        ],
        'bench': [
            {'name': 'איוון כרדל',              'number': 12, 'position': 'GK',  'club': 'דינמו זגרב'},
            {'name': 'דיוגו יוצ׳יץ׳',           'number': 6,  'position': 'DEF', 'club': 'אמוריאל'},
            {'name': 'ניקולה ולאשיץ׳',          'number': 14, 'position': 'MID', 'club': 'טורינו'},
            {'name': 'לוקה סוצ׳יץ׳',            'number': 15, 'position': 'MID', 'club': 'דינמו זגרב'},
            {'name': 'מריו פסאליץ׳',            'number': 16, 'position': 'MID', 'club': 'אטלנטה'},
        ],
    },

    'gha': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'לורנס אטי-זיגי',          'number': 1,  'position': 'GK',  'club': 'קריסטל פאלאס'},
            {'name': 'טארי ביינג׳',             'number': 2,  'position': 'DEF', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'דניאל אמרטי',             'number': 5,  'position': 'DEF', 'club': 'ניוקאסל'},
            {'name': 'מוחמד סלישו',             'number': 6,  'position': 'DEF', 'club': 'סאות׳המפטון'},
            {'name': 'עבד-ראחמן בבא',           'number': 3,  'position': 'DEF', 'club': 'פורטו'},
            {'name': 'תומאס פרטי',              'number': 8,  'position': 'MID', 'club': 'אלגזירה'},
            {'name': 'מינג׳ אמינה',             'number': 4,  'position': 'MID', 'club': 'אוסאסונה'},
            {'name': 'אנדרה אידין-ד׳איה',       'number': 7,  'position': 'MID', 'club': 'אנדרלכט'},
            {'name': 'עמנואל ד׳ייוס',           'number': 11, 'position': 'FWD', 'club': 'קריסטל פאלאס'},
            {'name': 'ג׳ורדן אייו',             'number': 9,  'position': 'FWD', 'club': 'ניס'},
            {'name': 'אינאקי ויליאמס',          'number': 10, 'position': 'FWD', 'club': 'אתלטיק בילבאו'},
        ],
        'bench': [
            {'name': 'ג׳וזף וומנסה',            'number': 22, 'position': 'GK',  'club': 'לאטס'},
            {'name': 'אלכסנדר ביאה',            'number': 14, 'position': 'DEF', 'club': 'ריינס'},
            {'name': 'בפר מנסה',                'number': 17, 'position': 'MID', 'club': 'קייפ קוסט'},
            {'name': 'אנטוניו מולבה',           'number': 15, 'position': 'FWD', 'club': 'ויכם'},
            {'name': 'ד׳ניאל אבנה',             'number': 20, 'position': 'FWD', 'club': 'ניוקאסל'},
        ],
    },

    'pan': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'לואיס מגיין',             'number': 1,  'position': 'GK',  'club': 'DC יונייטד'},
            {'name': 'מייקל מוריס',             'number': 2,  'position': 'DEF', 'club': 'לא- FC'},
            {'name': 'הרולד קאמינגס',           'number': 5,  'position': 'DEF', 'club': 'סאנדרלנד'},
            {'name': 'אניבל גוד׳וי',            'number': 6,  'position': 'DEF', 'club': 'נורוויץ׳'},
            {'name': 'אריס מלאנה',              'number': 3,  'position': 'DEF', 'club': 'קולוניה'},
            {'name': 'עאדולפו מאצ׳אדו',        'number': 8,  'position': 'MID', 'club': 'פנמה סיטי'},
            {'name': 'אריה בארת',              'number': 4,  'position': 'MID', 'club': 'טבס'},
            {'name': 'חוסה פינאלס',            'number': 7,  'position': 'MID', 'club': 'NY ריד בולס'},
            {'name': 'רולנד ד׳יסס',            'number': 11, 'position': 'MID', 'club': 'DC יונייטד'},
            {'name': 'גבריאל טורס',            'number': 10, 'position': 'FWD', 'club': 'ניוקאסל'},
            {'name': 'איסמאאיל דיאז',          'number': 9,  'position': 'FWD', 'club': 'ווסטהאם'},
        ],
        'bench': [
            {'name': 'ג׳ייסון נ׳דייב',          'number': 12, 'position': 'GK',  'club': 'פנמה סיטי'},
            {'name': 'ג׳וזה מרטינס',           'number': 15, 'position': 'DEF', 'club': 'טורינו'},
            {'name': 'ג׳ירמן ד׳ניאלס',         'number': 16, 'position': 'MID', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'פליפה בלוי',             'number': 17, 'position': 'FWD', 'club': 'וקנקובר'},
            {'name': 'ב׳רנרדו בתיסטה',         'number': 19, 'position': 'FWD', 'club': 'מיאמי FC'},
        ],
    },
}
