# Groups E-H (Germany, Curaçao, Ivory Coast, Ecuador,
#             Netherlands, Japan, Sweden, Tunisia,
#             Belgium, Egypt, Iran, New Zealand,
#             Spain, Cape Verde, Saudi Arabia, Uruguay)

squads_part2 = {

    # ── GROUP E ──────────────────────────────────────────────────────────────

    'ger': {
        'formation': '4-2-3-1',
        'starters': [
            {'name': 'מנואל נוייר',       'number': 1,  'position': 'GK',  'club': 'באיירן מינכן'},
            {'name': 'יושוה קימיך',       'number': 6,  'position': 'DEF', 'club': 'באיירן מינכן'},
            {'name': 'אנטוניו רודיגר',    'number': 5,  'position': 'DEF', 'club': 'ריאל מדריד'},
            {'name': 'ניקלאס זלה',        'number': 4,  'position': 'DEF', 'club': 'בורוסיה דורטמונד'},
            {'name': 'דאוד ריקסן',        'number': 3,  'position': 'DEF', 'club': 'בורוסיה דורטמונד'},
            {'name': 'רוברט אנדריך',      'number': 23, 'position': 'MID', 'club': 'לברקוזן'},
            {'name': 'פלוריאן ווירץ',     'number': 10, 'position': 'MID', 'club': 'לברקוזן'},
            {'name': 'לאיון מוסיאלה',     'number': 7,  'position': 'MID', 'club': 'באיירן מינכן'},
            {'name': 'ז׳אמל מוסיאלה',    'number': 17, 'position': 'MID', 'club': 'באיירן מינכן'},
            {'name': 'לוקאס נמצ׳קה',      'number': 9,  'position': 'MID', 'club': 'בורוסיה דורטמונד'},
            {'name': 'קאי הוורץ',         'number': 11, 'position': 'FWD', 'club': 'ארסנל'},
        ],
        'bench': [
            {'name': 'מרק-אנדרה טר שטגן', 'number': 12, 'position': 'GK',  'club': 'בארסלונה'},
            {'name': 'תילו קרר',           'number': 2,  'position': 'DEF', 'club': 'בארסלונה'},
            {'name': 'יוליאן בראנדט',      'number': 8,  'position': 'MID', 'club': 'בורוסיה דורטמונד'},
            {'name': 'ניקלאס פולקרוג',     'number': 9,  'position': 'FWD', 'club': 'ווסטהאם'},
            {'name': 'מקסימיליאן מיטלשטדט','number': 18, 'position': 'DEF', 'club': 'שטוטגרט'},
        ],
    },

    'cur': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'גוסטאבו פינה',      'number': 1,  'position': 'GK',  'club': 'הרינלם'},
            {'name': 'קנת׳ גוזלינג',      'number': 2,  'position': 'DEF', 'club': 'הרינלם'},
            {'name': 'צ׳נרי דיגנא',       'number': 5,  'position': 'DEF', 'club': 'וילם II'},
            {'name': 'גלן אקבו',           'number': 6,  'position': 'DEF', 'club': 'NEC ניימחן'},
            {'name': 'טיאנגו ציאקו',       'number': 3,  'position': 'DEF', 'club': 'ויטס'},
            {'name': 'צ׳רד גלנטה',        'number': 8,  'position': 'MID', 'club': 'Roda JC'},
            {'name': 'לוריק קנה',          'number': 4,  'position': 'MID', 'club': 'Telstar'},
            {'name': 'ריאנו פאולסן',       'number': 7,  'position': 'MID', 'club': 'הרינלם'},
            {'name': 'ג׳נירו ריינדורף',   'number': 11, 'position': 'MID', 'club': 'שלקה'},
            {'name': 'לאיון גר',           'number': 9,  'position': 'FWD', 'club': 'ויטס'},
            {'name': 'יאריך מרסלינה',     'number': 10, 'position': 'FWD', 'club': 'מאלמה'},
        ],
        'bench': [
            {'name': 'ג׳ינו ואן הוסן',    'number': 13, 'position': 'GK',  'club': 'אלמלו'},
            {'name': 'טאגנ בריטו',         'number': 14, 'position': 'DEF', 'club': 'בינגן'},
            {'name': 'צ׳לסי פריירה',      'number': 17, 'position': 'MID', 'club': 'קוראסאו'},
            {'name': 'ניבולו יאנסן',       'number': 19, 'position': 'FWD', 'club': 'הלאס'},
            {'name': 'ג׳וניאל ואלנטין',   'number': 20, 'position': 'FWD', 'club': 'Roda JC'},
        ],
    },

    'civ': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'אלטיצ׳ דייאיי',    'number': 1,  'position': 'GK',  'club': 'ניס'},
            {'name': 'אמד טוטה',           'number': 2,  'position': 'DEF', 'club': 'ונציה'},
            {'name': 'סרז׳' קוסנו',       'number': 5,  'position': 'DEF', 'club': 'מולדה'},
            {'name': 'אריק בריי',          'number': 6,  'position': 'DEF', 'club': 'אורלאן'},
            {'name': 'ווילפריד ז׳ניוה',   'number': 3,  'position': 'DEF', 'club': 'ברסט'},
            {'name': 'פרנק קסה',           'number': 8,  'position': 'MID', 'club': 'ריים'},
            {'name': 'ז׳אן מייקל סרי',    'number': 4,  'position': 'MID', 'club': 'לוהאבר'},
            {'name': 'סקו פוביאן',         'number': 7,  'position': 'MID', 'club': 'פרנקפורט'},
            {'name': 'ניקולאס פה',         'number': 11, 'position': 'FWD', 'club': 'ניס'},
            {'name': 'ז׳ון נגוסאן',        'number': 9,  'position': 'FWD', 'club': 'אינטר'},
            {'name': 'סימון אדינגרא',      'number': 10, 'position': 'FWD', 'club': 'ברייטון'},
        ],
        'bench': [
            {'name': 'בדי אונאנה',         'number': 16, 'position': 'GK',  'club': 'מארסל'},
            {'name': 'וויה ה', 'number': 15, 'position': 'DEF', 'club': 'ASEC מימוסה'},
            {'name': 'מקסוול קורנה',       'number': 17, 'position': 'MID', 'club': 'סיאון'},
            {'name': 'חמד טראורה',         'number': 19, 'position': 'FWD', 'club': 'בורנמות׳'},
            {'name': 'ויקטור אוסימהן',     'number': 21, 'position': 'FWD', 'club': 'נאפולי'},
        ],
    },

    'ecu': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'הרנן גאיינדה',      'number': 1,  'position': 'GK',  'club': 'ליגה דה קיטו'},
            {'name': 'אנחל מנה',           'number': 2,  'position': 'DEF', 'club': 'טורינו'},
            {'name': 'פיירס קאייסדו',      'number': 5,  'position': 'DEF', 'club': 'ברייטון'},
            {'name': 'פאקסון יאנסן',       'number': 6,  'position': 'DEF', 'club': 'Roda JC'},
            {'name': 'פרלין הינקפי',       'number': 3,  'position': 'DEF', 'club': 'NYC FC'},
            {'name': 'מויסס קאייסדו',      'number': 8,  'position': 'MID', 'club': 'צ׳לסי'},
            {'name': 'קרלוס גרואיסו',     'number': 16, 'position': 'MID', 'club': 'קיטו'},
            {'name': 'רומריו איבארה',      'number': 11, 'position': 'MID', 'club': 'פנאלקול'},
            {'name': 'גונסאלו פלאסיוס',    'number': 7,  'position': 'MID', 'club': 'ברייאה'},
            {'name': 'מייקל אסטרדה',      'number': 10, 'position': 'FWD', 'club': 'מונטריי'},
            {'name': 'אנר וולנסיה',        'number': 9,  'position': 'FWD', 'club': 'פנאלקול'},
        ],
        'bench': [
            {'name': 'אלכסנדר דומינגז',   'number': 12, 'position': 'GK',  'club': 'ליגה דה קיטו'},
            {'name': 'רוברט ארבולדה',      'number': 4,  'position': 'DEF', 'club': 'אל-נסר'},
            {'name': 'הרנן גאיינדה',      'number': 17, 'position': 'MID', 'club': 'ברייאה'},
            {'name': 'ג׳ורדן קסרס',       'number': 14, 'position': 'MID', 'club': 'ספרטה פראג'},
            {'name': 'ג׳ויס ווינה',        'number': 19, 'position': 'FWD', 'club': 'ספרטה פראג'},
        ],
    },

    # ── GROUP F ──────────────────────────────────────────────────────────────

    'ned': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'ברט ורברוגן',       'number': 1,  'position': 'GK',  'club': 'ארסנל'},
            {'name': 'דניזל דומפריס',     'number': 2,  'position': 'DEF', 'club': 'אינטר'},
            {'name': 'וירגיל ון דייק',    'number': 4,  'position': 'DEF', 'club': 'ליברפול'},
            {'name': 'סטפן דה ווריי',     'number': 6,  'position': 'DEF', 'club': 'אינטר'},
            {'name': 'ניקו שולץ',          'number': 3,  'position': 'DEF', 'club': 'ונציה'},
            {'name': 'פרנקי דה יונג',     'number': 8,  'position': 'MID', 'club': 'בארסלונה'},
            {'name': 'ג׳ורגיניו ווינאלדום','number': 6,  'position': 'MID', 'club': 'אל-אתיחאד'},
            {'name': 'טיאגו אלקנטרה',     'number': 18, 'position': 'MID', 'club': 'ליברפול'},
            {'name': 'סטיבן ברגהויס',     'number': 7,  'position': 'FWD', 'club': 'פנרבהצ׳ה'},
            {'name': 'מאמפיס דפאי',       'number': 9,  'position': 'FWD', 'club': 'אטלטיקו מדריד'},
            {'name': 'קודי גאקפו',         'number': 11, 'position': 'FWD', 'club': 'ליברפול'},
        ],
        'bench': [
            {'name': 'ג׳סטין ביגוף',      'number': 13, 'position': 'GK',  'club': 'ברייטון'},
            {'name': 'מתיאס דה ליגט',     'number': 5,  'position': 'DEF', 'club': 'מנצ׳סטר יונייטד'},
            {'name': 'יוסיף גאקפו',        'number': 17, 'position': 'MID', 'club': 'PSV'},
            {'name': 'ז׳אווי סימונס',      'number': 10, 'position': 'MID', 'club': 'PSG'},
            {'name': 'ואוט וגהורסט',      'number': 19, 'position': 'FWD', 'club': 'ווסטהאם'},
        ],
    },

    'jpn': {
        'formation': '4-2-3-1',
        'starters': [
            {'name': 'שוצ׳י גונדה',        'number': 1,  'position': 'GK',  'club': 'סנט-טרואן'},
            {'name': 'הירוקי סאקאי',       'number': 2,  'position': 'DEF', 'club': 'G-אוסאקה'},
            {'name': 'קו איטאקורה',        'number': 4,  'position': 'DEF', 'club': 'בורוסיה מ-גלדבך'},
            {'name': 'שוגו טאנגוצ׳י',     'number': 6,  'position': 'DEF', 'club': 'גירונה'},
            {'name': 'יוטו מאצ׳ידה',       'number': 5,  'position': 'DEF', 'club': 'קאשימה'},
            {'name': 'הירוקי מיטומה',      'number': 10, 'position': 'MID', 'club': 'ברייטון'},
            {'name': 'וואטארו אנדו',        'number': 7,  'position': 'MID', 'club': 'ליברפול'},
            {'name': 'ריוטרו הטאגי',       'number': 8,  'position': 'MID', 'club': 'שטוטגרט'},
            {'name': 'דאיצ׳י קאמאדה',      'number': 14, 'position': 'MID', 'club': 'לאציו'},
            {'name': 'קאורו מיטומה',        'number': 11, 'position': 'MID', 'club': 'ברייטון'},
            {'name': 'אייסיה מורינו',       'number': 9,  'position': 'FWD', 'club': 'G-אוסאקה'},
        ],
        'bench': [
            {'name': 'זיון שינמוטו',        'number': 12, 'position': 'GK',  'club': 'קאשימה'},
            {'name': 'שוטארו מיימוטו',      'number': 15, 'position': 'DEF', 'club': 'NEC ניימחן'},
            {'name': 'יוקי סוגאוארה',       'number': 13, 'position': 'DEF', 'club': 'AZ אלקמאר'},
            {'name': 'טאקהירו טומייאסו',   'number': 17, 'position': 'DEF', 'club': 'ארסנל'},
            {'name': 'קאינה',               'number': 19, 'position': 'FWD', 'club': 'פלמנגו'},
        ],
    },

    'swe': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'רובין אולסן',         'number': 1,  'position': 'GK',  'club': 'סאות׳המפטון'},
            {'name': 'ג׳נס בדמן',           'number': 2,  'position': 'DEF', 'club': 'מגדבורג'},
            {'name': 'וויקטור נילסון לינד', 'number': 5,  'position': 'DEF', 'club': 'פנרבהצ׳ה'},
            {'name': 'אמיל קרפט',           'number': 6,  'position': 'DEF', 'club': 'קלן'},
            {'name': 'לוקאס אולסון',        'number': 3,  'position': 'DEF', 'club': 'פרנקפורט'},
            {'name': 'קרספר אסגרן',         'number': 8,  'position': 'MID', 'club': 'בורוסיה דורטמונד'},
            {'name': 'אסאיאס כיידאן',       'number': 4,  'position': 'MID', 'club': 'שלקה'},
            {'name': 'קרל מולאנד',          'number': 7,  'position': 'MID', 'club': 'ניס'},
            {'name': 'אנטוניו קוסקלה',      'number': 11, 'position': 'FWD', 'club': 'ניוקאסל'},
            {'name': 'ג׳ים מאייר',          'number': 9,  'position': 'FWD', 'club': 'לברקוזן'},
            {'name': 'אלכסנדר אסלוג',       'number': 10, 'position': 'FWD', 'club': 'בורוסיה דורטמונד'},
        ],
        'bench': [
            {'name': 'קרל יוהנסון',         'number': 12, 'position': 'GK',  'club': 'מלמה'},
            {'name': 'מיקאל לוסטיג',        'number': 14, 'position': 'DEF', 'club': 'IFK גטבורג'},
            {'name': 'ז׳ן-קרלוס פאס',       'number': 17, 'position': 'MID', 'club': 'ברייטון'},
            {'name': 'לאגרבק לינד',          'number': 19, 'position': 'FWD', 'club': 'שלקה'},
            {'name': 'מרקוס רדסטדה',        'number': 20, 'position': 'FWD', 'club': 'מלמה'},
        ],
    },

    'tun': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'אייוב גניא',          'number': 1,  'position': 'GK',  'club': 'אל-קאהרה'},
            {'name': 'מחמד דרגר',           'number': 2,  'position': 'DEF', 'club': 'לוהאבר'},
            {'name': 'יאסין מריאה',         'number': 5,  'position': 'DEF', 'club': 'אל-עין'},
            {'name': 'דיוסן בולה',          'number': 6,  'position': 'DEF', 'club': 'לברקוזן'},
            {'name': 'אלי ב׳יד',            'number': 3,  'position': 'DEF', 'club': 'לוהאבר'},
            {'name': 'חמזה אלדן',           'number': 8,  'position': 'MID', 'club': 'אספניול'},
            {'name': 'עסם בן-עלי',          'number': 4,  'position': 'MID', 'club': 'אל-קאהרה'},
            {'name': 'אניס בן-סלמה',        'number': 7,  'position': 'MID', 'club': 'אל-אתיחאד'},
            {'name': 'עלי מאלול',           'number': 3,  'position': 'MID', 'club': 'ראסינג'},
            {'name': 'ואחבי חזרי',          'number': 10, 'position': 'FWD', 'club': 'אל-שביב'},
            {'name': 'יוסף ג׳לסי',          'number': 9,  'position': 'FWD', 'club': 'לוהאבר'},
        ],
        'bench': [
            {'name': 'בכר בן-עאמר',         'number': 16, 'position': 'GK',  'club': 'אספרנס'},
            {'name': 'ז׳ן קלייר',           'number': 14, 'position': 'DEF', 'club': 'ניס'},
            {'name': 'עסם סאסי',             'number': 17, 'position': 'MID', 'club': 'אל-ראיאן'},
            {'name': 'פארחאן חוסייני',       'number': 19, 'position': 'MID', 'club': 'טרואה'},
            {'name': 'נדרי אירגי',           'number': 20, 'position': 'FWD', 'club': 'נאנסי'},
        ],
    },

    # ── GROUP G ──────────────────────────────────────────────────────────────

    'bel': {
        'formation': '3-4-3',
        'starters': [
            {'name': 'קנט קסטיליץ׳',       'number': 1,  'position': 'GK',  'club': 'הבסלה'},
            {'name': 'טובי אלדרוויילד',    'number': 4,  'position': 'DEF', 'club': 'אנטוורפן'},
            {'name': 'יאנניק קרסקן',       'number': 5,  'position': 'DEF', 'club': 'לכטה'},
            {'name': 'ורטונגן',             'number': 6,  'position': 'DEF', 'club': 'RSC אנדרלכט'},
            {'name': 'תומאס מיניה',         'number': 2,  'position': 'MID', 'club': 'בסיקטאש'},
            {'name': 'אקסל ווינקל',         'number': 7,  'position': 'MID', 'club': 'בריז׳ה'},
            {'name': 'אמינה עדלי',           'number': 8,  'position': 'MID', 'club': 'לאציו'},
            {'name': 'לאון בייל',            'number': 3,  'position': 'MID', 'club': 'גנט'},
            {'name': 'לואיס אופנדה',        'number': 11, 'position': 'FWD', 'club': 'נאפולי'},
            {'name': 'רומלו לוקאקו',         'number': 9,  'position': 'FWD', 'club': 'נאפולי'},
            {'name': 'ז׳רמי דוקו',          'number': 10, 'position': 'FWD', 'club': 'מנצ׳סטר סיטי'},
        ],
        'bench': [
            {'name': 'מאץ מאטס',             'number': 12, 'position': 'GK',  'club': 'ווסטהאם'},
            {'name': 'ד׳ריס מרטנס',         'number': 14, 'position': 'FWD', 'club': 'גלטסריי'},
            {'name': 'איבאן פריסניאנו',     'number': 17, 'position': 'MID', 'club': 'קלאב ברוז׳'},
            {'name': 'שרל דה קטלייר',       'number': 15, 'position': 'DEF', 'club': 'אנטוורפן'},
            {'name': 'ד׳אנה לנדרמן',        'number': 20, 'position': 'MID', 'club': 'גנט'},
        ],
    },

    'egy': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'מוחמד אל-שנאווי',     'number': 1,  'position': 'GK',  'club': 'אל-אהלי'},
            {'name': 'מוחמד אל-בחר',        'number': 2,  'position': 'DEF', 'club': 'זמאלק'},
            {'name': 'עומר קמאל',            'number': 5,  'position': 'DEF', 'club': 'אל-אהלי'},
            {'name': 'מוחמד עבדל-מונם',      'number': 6,  'position': 'DEF', 'club': 'פירנצה'},
            {'name': 'בשיר חאפז',            'number': 3,  'position': 'DEF', 'club': 'אל-אהלי'},
            {'name': 'מחמד אל-ננני',         'number': 8,  'position': 'MID', 'club': 'PAOK'},
            {'name': 'עמרו סולייה',          'number': 4,  'position': 'MID', 'club': 'אל-אתיחאד'},
            {'name': 'טריזגה',               'number': 7,  'position': 'MID', 'club': 'גלטסריי'},
            {'name': 'אחמד קשאק',            'number': 11, 'position': 'MID', 'club': 'פנרבהצ׳ה'},
            {'name': 'מוחמד סאלח',           'number': 10, 'position': 'FWD', 'club': 'ליברפול'},
            {'name': 'מרוואן עטיה',          'number': 9,  'position': 'FWD', 'club': 'אל-אהלי'},
        ],
        'bench': [
            {'name': 'עאמר אמנגל',           'number': 13, 'position': 'GK',  'club': 'זמאלק'},
            {'name': 'ז׳א שחאתה',            'number': 15, 'position': 'DEF', 'club': 'אל-אהלי'},
            {'name': 'אחמד נבי',             'number': 17, 'position': 'MID', 'club': 'פירנצה'},
            {'name': 'עמרו וארדה',           'number': 14, 'position': 'FWD', 'club': 'פאנאת׳ינאיקוס'},
            {'name': 'מוסטפא מוחמד',         'number': 9,  'position': 'FWD', 'club': 'גנט'},
        ],
    },

    'irn': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'עלירזה בירנוונד',      'number': 1,  'position': 'GK',  'club': 'לובוס'},
            {'name': 'שוג׳אע חלילזאדה',     'number': 2,  'position': 'DEF', 'club': 'פרספוליס'},
            {'name': 'מיל׳אד מוחמדי',       'number': 5,  'position': 'DEF', 'club': 'Sepahan'},
            {'name': 'עבולפצ׳ל עמיריאן',    'number': 6,  'position': 'DEF', 'club': 'ספאהאן'},
            {'name': 'אחמד נורי',            'number': 3,  'position': 'DEF', 'club': 'פרספוליס'},
            {'name': 'סג׳אד שהבזאדה',       'number': 8,  'position': 'MID', 'club': 'אסטאנה'},
            {'name': 'עלי קאסמי',            'number': 4,  'position': 'MID', 'club': 'AL-דוחאיל'},
            {'name': 'מהדי טארמי',           'number': 7,  'position': 'MID', 'club': 'PSG'},
            {'name': 'עלירזה ג׳הנבחש',      'number': 11, 'position': 'MID', 'club': 'טבריז'},
            {'name': 'קרים אנסארי-פארד',    'number': 9,  'position': 'FWD', 'club': 'אנסבאך'},
            {'name': 'סרדאר אזמון',          'number': 10, 'position': 'FWD', 'club': 'אל-קדסייה'},
        ],
        'bench': [
            {'name': 'מחסן פורוגנג',         'number': 12, 'position': 'GK',  'club': 'ספאהאן'},
            {'name': 'ח׳ון נאסרי',           'number': 15, 'position': 'DEF', 'club': 'Persepolis'},
            {'name': 'עלי גלולי',            'number': 17, 'position': 'MID', 'club': 'אסתגלל'},
            {'name': 'אמיר ארסלן מוטגי',    'number': 19, 'position': 'MID', 'club': 'Persepolis'},
            {'name': 'מוחמד קאנאאני זדה',    'number': 20, 'position': 'FWD', 'club': 'טבריז'},
        ],
    },

    'nzl': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'מקס כלוד',            'number': 1,  'position': 'GK',  'club': 'ווסטרן יונייטד'},
            {'name': 'לוגן גוגולי',         'number': 2,  'position': 'DEF', 'club': 'ווסטרן יונייטד'},
            {'name': 'נואה גמיין',          'number': 5,  'position': 'DEF', 'club': 'הוורד'},
            {'name': 'מייקל ווקר',          'number': 6,  'position': 'DEF', 'club': 'אינסברוק'},
            {'name': 'ב׳יל סאמוויל',        'number': 3,  'position': 'DEF', 'club': 'ג׳נרוניימו'},
            {'name': 'נולן ריד',             'number': 8,  'position': 'MID', 'club': 'פורטלנד'},
            {'name': 'מרקוס אינגרם',        'number': 4,  'position': 'MID', 'club': 'ווסטרן יונייטד'},
            {'name': 'קנדי לואיס',          'number': 7,  'position': 'MID', 'club': 'הוורד'},
            {'name': 'ג׳יין קאונט',         'number': 11, 'position': 'MID', 'club': 'ווינגטון'},
            {'name': 'חריס ד׳אטנב',        'number': 9,  'position': 'FWD', 'club': 'הוורד'},
            {'name': 'כריס וד',             'number': 10, 'position': 'FWD', 'club': 'ווסטרן יונייטד'},
        ],
        'bench': [
            {'name': 'ריאן תומאס',          'number': 13, 'position': 'GK',  'club': 'ואלינגטון'},
            {'name': 'אמיר לואיס',          'number': 15, 'position': 'DEF', 'club': 'אוקלנד'},
            {'name': 'בן ד׳שוסטר',         'number': 17, 'position': 'MID', 'club': 'ניו-זילנד'},
            {'name': 'ויל אנדרוז',          'number': 14, 'position': 'MID', 'club': 'ווסטרן יונייטד'},
            {'name': 'ג׳ו בל',              'number': 19, 'position': 'FWD', 'club': 'הוורד'},
        ],
    },

    # ── GROUP H ──────────────────────────────────────────────────────────────

    'esp': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'אונאי סימון',          'number': 1,  'position': 'GK',  'club': 'אתלטיק בילבאו'},
            {'name': 'דני קרבחל',            'number': 2,  'position': 'DEF', 'club': 'ריאל מדריד'},
            {'name': 'אינייגו מרטינס',       'number': 4,  'position': 'DEF', 'club': 'בארסלונה'},
            {'name': 'רובן לה נורמן',        'number': 6,  'position': 'DEF', 'club': 'לאציו'},
            {'name': 'מרקוס אקוניה',         'number': 3,  'position': 'DEF', 'club': 'ספרטה רוטרדם'},
            {'name': 'רודרי',                'number': 16, 'position': 'MID', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'פאביאן רויז',          'number': 8,  'position': 'MID', 'club': 'PSG'},
            {'name': 'פדרי',                 'number': 26, 'position': 'MID', 'club': 'בארסלונה'},
            {'name': 'ניקו וויליאמס',        'number': 11, 'position': 'FWD', 'club': 'אתלטיק בילבאו'},
            {'name': 'אלוורו מוראטה',        'number': 7,  'position': 'FWD', 'club': 'AC מילאן'},
            {'name': 'ל׳מין יאמל',           'number': 19, 'position': 'FWD', 'club': 'בארסלונה'},
        ],
        'bench': [
            {'name': 'רובן בלוקיז',          'number': 13, 'position': 'GK',  'club': 'ויאריאל'},
            {'name': 'איימריק לאפורט',       'number': 14, 'position': 'DEF', 'club': 'אל-נסר'},
            {'name': 'פרן טורס',             'number': 17, 'position': 'FWD', 'club': 'בארסלונה'},
            {'name': 'פבלו ג׳ן-לוק',         'number': 21, 'position': 'MID', 'club': 'ריאל מדריד'},
            {'name': 'הוסיה מוראטה',         'number': 22, 'position': 'FWD', 'club': 'ספרטה'},
        ],
    },

    'cpv': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'ויקטור מנדס',          'number': 1,  'position': 'GK',  'club': 'פריירה'},
            {'name': 'ג׳וניאל ג׳ורז׳',       'number': 2,  'position': 'DEF', 'club': 'ספרטה פראג'},
            {'name': 'דיוגו נ׳הטנה',          'number': 5,  'position': 'DEF', 'club': 'מרסיי'},
            {'name': 'פביאן מה',              'number': 6,  'position': 'DEF', 'club': 'ביירות'},
            {'name': 'ג׳ון לנינה',            'number': 3,  'position': 'DEF', 'club': 'ויקטוריה SC'},
            {'name': 'נבוש לוה',              'number': 8,  'position': 'MID', 'club': 'אינטרנשיונל'},
            {'name': 'ז׳ון מריה מורייר',     'number': 4,  'position': 'MID', 'club': 'פריירה'},
            {'name': 'ריאן לובוז',            'number': 7,  'position': 'MID', 'club': 'CS מריטמו'},
            {'name': 'ג׳ייסון לופס',          'number': 11, 'position': 'MID', 'club': 'אודינזה'},
            {'name': 'רוניו וינסנט',          'number': 9,  'position': 'FWD', 'club': 'ספרטה פראג'},
            {'name': 'ג׳ילסון ד׳אלמיידה',    'number': 10, 'position': 'FWD', 'club': 'ויקטוריה SC'},
        ],
        'bench': [
            {'name': 'מנואל פרנאנדס',        'number': 16, 'position': 'GK',  'club': 'CS מריטמו'},
            {'name': 'פליפה מלו',             'number': 15, 'position': 'DEF', 'club': 'פריירה'},
            {'name': 'קוואמה',                'number': 17, 'position': 'MID', 'club': 'ביירות'},
            {'name': 'ג׳ייסון ד׳ולאנו',      'number': 14, 'position': 'FWD', 'club': 'CS מריטמו'},
            {'name': 'ג׳וניאל פמינה',        'number': 19, 'position': 'FWD', 'club': 'ויקטוריה SC'},
        ],
    },

    'ksa': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'מוחמד אל-עווד',        'number': 1,  'position': 'GK',  'club': 'אל-הילאל'},
            {'name': 'עבדלחמיד אל-דוסארי',  'number': 2,  'position': 'DEF', 'club': 'אל-הילאל'},
            {'name': 'עלי אל-בולאיחי',       'number': 5,  'position': 'DEF', 'club': 'אל-הילאל'},
            {'name': 'אבראהים אל-קראן',       'number': 6,  'position': 'DEF', 'club': 'אל-אתיחאד'},
            {'name': 'יאסר אל-שהראני',       'number': 3,  'position': 'DEF', 'club': 'אל-הילאל'},
            {'name': 'עסם אל-שהרי',           'number': 7,  'position': 'MID', 'club': 'אל-הילאל'},
            {'name': 'עמד אל-פארג׳',         'number': 4,  'position': 'MID', 'club': 'אל-הילאל'},
            {'name': 'מוחמד קנו',             'number': 8,  'position': 'MID', 'club': 'אל-אתיחאד'},
            {'name': 'פיראס אל-ברייקאן',     'number': 11, 'position': 'MID', 'club': 'אל-אתיחאד'},
            {'name': 'סלם אל-דוסארי',        'number': 10, 'position': 'FWD', 'club': 'אל-הילאל'},
            {'name': 'מרוואן אל-שהרי',       'number': 9,  'position': 'FWD', 'club': 'אל-קדסייה'},
        ],
        'bench': [
            {'name': 'פאראג׳ עמר',            'number': 21, 'position': 'GK',  'club': 'אל-נסר'},
            {'name': 'סאוד עבד-אלחמיד',      'number': 13, 'position': 'DEF', 'club': 'אינטר'},
            {'name': 'האיתם עסיר',            'number': 17, 'position': 'MID', 'club': 'אל-הילאל'},
            {'name': 'נאסר אל-דוסארי',       'number': 16, 'position': 'FWD', 'club': 'אל-פתח'},
            {'name': 'מוחמד מארן',            'number': 14, 'position': 'FWD', 'club': 'אל-אהלי (SA)'},
        ],
    },

    'uru': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'סבסטיאן סוסה',         'number': 1,  'position': 'GK',  'club': 'נסיונל'},
            {'name': 'חואן פריה',             'number': 2,  'position': 'DEF', 'club': 'ויאריאל'},
            {'name': 'ד׳יאגו גודין',          'number': 3,  'position': 'DEF', 'club': 'פנרבהצ׳ה'},
            {'name': 'רונאלד ארגייסוא',       'number': 6,  'position': 'DEF', 'club': 'ריבר פלייט'},
            {'name': 'מטיאס ויניה',           'number': 22, 'position': 'DEF', 'club': 'ריאל מדריד'},
            {'name': 'לוקאס טורייר',          'number': 8,  'position': 'MID', 'club': 'מונאקו'},
            {'name': 'מנואל אוגארטה',         'number': 15, 'position': 'MID', 'club': 'מנצ׳סטר יונייטד'},
            {'name': 'פדרו אקינו',            'number': 7,  'position': 'MID', 'club': 'אינטר'},
            {'name': 'פדרו גונסאלס',          'number': 11, 'position': 'FWD', 'club': 'בארסלונה'},
            {'name': 'דרווין נונס',           'number': 9,  'position': 'FWD', 'club': 'ליברפול'},
            {'name': 'פאקונדו פלסטרי',        'number': 10, 'position': 'FWD', 'club': 'נאפולי'},
        ],
        'bench': [
            {'name': 'פרנאנדו מוסלרה',        'number': 13, 'position': 'GK',  'club': 'נסיונל'},
            {'name': 'מרטין קסרס',            'number': 5,  'position': 'DEF', 'club': 'גנרל'},
            {'name': 'נאהואל מולינה',         'number': 17, 'position': 'DEF', 'club': 'אטלטיקו מדריד'},
            {'name': 'ג׳ורג׳יאן דה אראסקאטה', 'number': 14, 'position': 'MID', 'club': 'ריבר פלייט'},
            {'name': 'ניקולאס ד׳אלברטי',     'number': 19, 'position': 'FWD', 'club': 'ריאל מדריד'},
        ],
    },
}
