# Groups A-D (Mexico, South Africa, South Korea, Czech Republic,
#             Canada, Bosnia, Qatar, Switzerland,
#             Brazil, Morocco, Haiti, Scotland,
#             USA, Paraguay, Australia, Turkey)

squads_part1 = {

    # ── GROUP A ──────────────────────────────────────────────────────────────

    'mex': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'גיום אוצ׳וה', 'number': 1,  'position': 'GK',  'club': 'LAFC'},
            {'name': 'חורחה סנצ׳ס',  'number': 23, 'position': 'DEF', 'club': 'אמריקה'},
            {'name': 'סזר מונטס',     'number': 3,  'position': 'DEF', 'club': 'מונטריי'},
            {'name': 'חוהאן ואסקס',   'number': 4,  'position': 'DEF', 'club': 'פאצ׳וקה'},
            {'name': 'גרארדו ארטאגה', 'number': 17, 'position': 'DEF', 'club': 'בטיס'},
            {'name': 'אדרי גוארדאדו', 'number': 18, 'position': 'MID', 'club': 'צ׳יאפס'},
            {'name': 'אדסון אלברס',   'number': 8,  'position': 'MID', 'club': 'גדלחרה'},
            {'name': 'סבסטיאן קורדובה','number': 16, 'position': 'MID', 'club': 'טיגרס'},
            {'name': 'חירמן לוזאנו',  'number': 22, 'position': 'FWD', 'club': 'PSV'},
            {'name': 'הנרי מרטין',    'number': 14, 'position': 'FWD', 'club': 'אמריקה'},
            {'name': 'סנטיאגו חימנס', 'number': 9,  'position': 'FWD', 'club': 'פיינורד'},
        ],
        'bench': [
            {'name': 'רודולפו קוטה',   'number': 13, 'position': 'GK',  'club': 'צ׳יאפס'},
            {'name': 'לואיס צ׳אבס',    'number': 5,  'position': 'DEF', 'club': 'פורטו'},
            {'name': 'אוריבה פראלטה',  'number': 7,  'position': 'FWD', 'club': 'גדלחרה'},
            {'name': 'רוברטו אלבארס',  'number': 10, 'position': 'MID', 'club': 'לאון'},
            {'name': 'אנתוני לופס',    'number': 21, 'position': 'FWD', 'club': 'טולוקה'},
        ],
    },

    'rsa': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'רונדווה וויליאמס', 'number': 1,  'position': 'GK',  'club': 'מאמלודי סאנדאונס'},
            {'name': 'ריידהן גריגורי',   'number': 2,  'position': 'DEF', 'club': 'קייפ טאון סיטי'},
            {'name': 'יוהן מוהלינגו',    'number': 5,  'position': 'DEF', 'club': 'מאמלודי סאנדאונס'},
            {'name': 'סיפו מוקוניה',     'number': 6,  'position': 'DEF', 'club': 'אורלנדו פיירייטס'},
            {'name': 'ניאל דה לנגה',    'number': 3,  'position': 'DEF', 'club': 'קייפ טאון סיטי'},
            {'name': 'ת׳אבו נוצ׳ה',     'number': 8,  'position': 'MID', 'club': 'מאמלודי סאנדאונס'},
            {'name': 'בונגאני זולו',     'number': 4,  'position': 'MID', 'club': 'סופר ספורט יונייטד'},
            {'name': 'תבו קוטלסי',      'number': 7,  'position': 'MID', 'club': 'קייפ טאון סיטי'},
            {'name': 'מגאלי מוצ׳אנגה',  'number': 11, 'position': 'MID', 'club': 'אורלנדו פיירייטס'},
            {'name': 'פרסי טאו',        'number': 10, 'position': 'FWD', 'club': 'אל-אהלי'},
            {'name': 'וינסטון רייד',     'number': 9,  'position': 'FWD', 'club': 'מאמלודי סאנדאונס'},
        ],
        'bench': [
            {'name': 'בריון ג׳קסון',    'number': 16, 'position': 'GK',  'club': 'קייפ טאון סיטי'},
            {'name': 'לוקאס מוגאמבי',   'number': 15, 'position': 'DEF', 'club': 'מאמלודי סאנדאונס'},
            {'name': 'ת׳אבאנג נוטסאנה', 'number': 17, 'position': 'MID', 'club': 'מאמלודי סאנדאונס'},
            {'name': 'לוקשה מרטינס',    'number': 19, 'position': 'FWD', 'club': 'TS גלקסי'},
            {'name': 'אובאקה נוואבי',    'number': 20, 'position': 'FWD', 'club': 'אורלנדו פיירייטס'},
        ],
    },

    'kor': {
        'formation': '4-2-3-1',
        'starters': [
            {'name': 'קים סאנג-גיון',   'number': 1,  'position': 'GK',  'club': 'ג׳אונבוק'},
            {'name': 'קים מין-ג׳ה',     'number': 3,  'position': 'DEF', 'club': 'באיירן מינכן'},
            {'name': 'קים יאנג-גון',    'number': 4,  'position': 'DEF', 'club': 'אל-קדסייה'},
            {'name': 'לי קי-ג׳ה',       'number': 2,  'position': 'DEF', 'club': 'מיאורה'},
            {'name': 'קים ג׳ין-סו',     'number': 23, 'position': 'DEF', 'club': 'PSV'},
            {'name': 'ג׳אנג ס-אין',     'number': 6,  'position': 'MID', 'club': 'מיאן'},
            {'name': 'ג׳ונג וו-יאונג',  'number': 16, 'position': 'MID', 'club': 'אינטר'},
            {'name': 'לי ג׳אה-סאנג',   'number': 17, 'position': 'MID', 'club': 'מיאורה'},
            {'name': 'לי קאנג-אין',     'number': 19, 'position': 'MID', 'club': 'פריז סן-ז׳רמן'},
            {'name': 'הוואנג הי-צ׳אן',  'number': 11, 'position': 'MID', 'club': 'וולברהמפטון'},
            {'name': 'סון הה-מין',      'number': 7,  'position': 'FWD', 'club': 'טוטנהם'},
        ],
        'bench': [
            {'name': 'חוואנג סאן-באום',  'number': 9,  'position': 'FWD', 'club': 'פרנקפורט'},
            {'name': 'קים ד-אין',        'number': 13, 'position': 'GK',  'club': 'ג׳אונבוק'},
            {'name': 'או ס-יון',         'number': 8,  'position': 'MID', 'club': 'מיאן'},
            {'name': 'לי ג׳ונג-יאונג',  'number': 14, 'position': 'MID', 'club': 'בולוניה'},
            {'name': 'צ׳ו גאה-ס',       'number': 20, 'position': 'DEF', 'club': 'ג׳אונבוק'},
        ],
    },

    'cze': {
        'formation': '4-2-3-1',
        'starters': [
            {'name': 'ג׳ירי פאבלנקה',   'number': 1,  'position': 'GK',  'club': 'ברמן'},
            {'name': 'ולדימיר קופל',    'number': 2,  'position': 'DEF', 'club': 'לאציו'},
            {'name': 'לאדיסלב קרג׳צ׳י', 'number': 5,  'position': 'DEF', 'club': 'פלזן'},
            {'name': 'דוד יורסקה',      'number': 6,  'position': 'DEF', 'club': 'הרתה'},
            {'name': 'יאן בורק',        'number': 3,  'position': 'DEF', 'club': 'פלזן'},
            {'name': 'אלכס קרדה',       'number': 8,  'position': 'MID', 'club': 'האמבורג'},
            {'name': 'טומאס סוצ׳ק',     'number': 6,  'position': 'MID', 'club': 'ווסטהאם'},
            {'name': 'לוקאש מסוצ׳קו',  'number': 10, 'position': 'MID', 'club': 'פלזן'},
            {'name': 'מיכאל סאדילק',    'number': 17, 'position': 'MID', 'club': 'סמפדוריה'},
            {'name': 'יאן קוצ׳טה',      'number': 7,  'position': 'MID', 'club': 'ניסה'},
            {'name': 'פטריק שיק',       'number': 9,  'position': 'FWD', 'club': 'לברקוזן'},
        ],
        'bench': [
            {'name': 'אונדרז׳ יוראצקה', 'number': 13, 'position': 'GK',  'club': 'פלזן'},
            {'name': 'דוד פוגאסיץ׳',    'number': 4,  'position': 'DEF', 'club': 'ספרטה פראג'},
            {'name': 'אדם הלוזק',       'number': 11, 'position': 'FWD', 'club': 'ספרטה פראג'},
            {'name': 'מתיאס פרוביוד',   'number': 19, 'position': 'MID', 'club': 'פלזן'},
            {'name': 'ולאס צ׳רמאק',     'number': 14, 'position': 'FWD', 'club': 'ג׳נואה'},
        ],
    },

    # ── GROUP B ──────────────────────────────────────────────────────────────

    'can': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'מקסים קרפ',       'number': 1,  'position': 'GK',  'club': 'אינטר מיאמי'},
            {'name': 'אשלי לורנס',      'number': 2,  'position': 'DEF', 'club': 'PSG'},
            {'name': 'קאיל מילר',        'number': 5,  'position': 'DEF', 'club': 'פולהאם'},
            {'name': 'ארניאוד נורמנד',  'number': 6,  'position': 'DEF', 'club': 'CF מונטריאל'},
            {'name': 'סם אדקס',          'number': 3,  'position': 'DEF', 'club': 'וקנקובר'},
            {'name': 'מארק-אנטואן פורטן','number': 8, 'position': 'MID', 'club': 'ניס'},
            {'name': 'איסמאל קונה',      'number': 4,  'position': 'MID', 'club': 'בורוסיה דורטמונד'},
            {'name': 'ג׳ונטן אוסוריו',   'number': 7,  'position': 'MID', 'club': 'טורונטו FC'},
            {'name': 'אלפונסו דיוויס',   'number': 19, 'position': 'FWD', 'club': 'ריאל מדריד'},
            {'name': 'טאיון בוקנן',      'number': 11, 'position': 'FWD', 'club': 'אינטר'},
            {'name': 'סיריל לם',         'number': 9,  'position': 'FWD', 'club': 'CF מונטריאל'},
        ],
        'bench': [
            {'name': 'מקסיאן לפמאן',    'number': 13, 'position': 'GK',  'club': 'ניוקאסל'},
            {'name': 'דרק קורנליוס',     'number': 10, 'position': 'FWD', 'club': 'פרמה'},
            {'name': 'צ׳ארלי מוגנה',    'number': 17, 'position': 'MID', 'club': 'ספורטינג'},
            {'name': 'קאמרון ווקר',      'number': 23, 'position': 'DEF', 'club': 'ניו-אינגלנד'},
            {'name': 'לוקאס קאבאיהו',   'number': 14, 'position': 'FWD', 'club': 'CF מונטריאל'},
        ],
    },

    'bih': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'ניקולה וסלייץ׳',   'number': 1,  'position': 'GK',  'club': 'זרינסקי'},
            {'name': 'אנס מהמוצ׳יץ׳',   'number': 2,  'position': 'DEF', 'club': 'זרינסקי'},
            {'name': 'אמיר ראמוביץ׳',   'number': 5,  'position': 'DEF', 'club': 'סרייבו'},
            {'name': 'בורנה סוסה',       'number': 6,  'position': 'DEF', 'club': 'טראבזונספור'},
            {'name': 'ג׳נאד היריץ׳',     'number': 3,  'position': 'DEF', 'club': 'מאלאגה'},
            {'name': 'ג׳סמין מוג׳יץ׳',  'number': 8,  'position': 'MID', 'club': 'פאניוניוס'},
            {'name': 'אריין קפריאנו',   'number': 16, 'position': 'MID', 'club': 'מאלגה'},
            {'name': 'סאד סאד',          'number': 7,  'position': 'MID', 'club': 'פרנקפורט'},
            {'name': 'ג׳נאל מוסטפיץ׳',  'number': 11, 'position': 'MID', 'club': 'קלארנבאך'},
            {'name': 'ארמין הודז׳יץ׳',  'number': 9,  'position': 'FWD', 'club': 'זרינסקי'},
            {'name': 'אדין ג׳קו',        'number': 10, 'position': 'FWD', 'club': 'פנרבהצ׳ה'},
        ],
        'bench': [
            {'name': 'בגיץ׳ עומאר',     'number': 13, 'position': 'GK',  'club': 'זרינסקי'},
            {'name': 'עמאר ביץ׳קצ׳יץ׳', 'number': 4,  'position': 'DEF', 'club': 'אנג׳י'},
            {'name': 'אדמיר מהמוצ׳יץ׳', 'number': 14, 'position': 'FWD', 'club': 'סרייבו'},
            {'name': 'אמיר חדז׳יץ׳',    'number': 17, 'position': 'MID', 'club': 'גרויטר פירת'},
            {'name': 'הריס סארמנוביץ׳', 'number': 19, 'position': 'FWD', 'club': 'אודינזה'},
        ],
    },

    'qat': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'משעל בארשם',       'number': 1,  'position': 'GK',  'club': 'אל-סד'},
            {'name': 'פדרו מיגל',        'number': 2,  'position': 'DEF', 'club': 'אל-סד'},
            {'name': 'בסם אל-ראוי',     'number': 5,  'position': 'DEF', 'club': 'אל-סד'},
            {'name': 'אבדלכרים חסן',     'number': 6,  'position': 'DEF', 'club': 'אל-אהלי'},
            {'name': 'הוסאם קבאר',       'number': 3,  'position': 'DEF', 'club': 'אל-ריאן'},
            {'name': 'קארים בוחדוז',     'number': 8,  'position': 'MID', 'club': 'אל-ריאן'},
            {'name': 'עבדאלעזיז חאתם',   'number': 14, 'position': 'MID', 'club': 'אל-ראיאן'},
            {'name': 'איסמאיל מוחמד',    'number': 7,  'position': 'MID', 'club': 'אל-ואקרה'},
            {'name': 'חמד מדאבו',        'number': 11, 'position': 'MID', 'club': 'אל-ריאן'},
            {'name': 'אלמועז עלי',       'number': 10, 'position': 'FWD', 'club': 'אל-דוחאיל'},
            {'name': 'פיסאל אל-נאסר',   'number': 9,  'position': 'FWD', 'club': 'אל-קדסייה'},
        ],
        'bench': [
            {'name': 'יוסוף הסן',        'number': 16, 'position': 'GK',  'club': 'אל-סד'},
            {'name': 'תריב קסאס',        'number': 4,  'position': 'DEF', 'club': 'אל-סד'},
            {'name': 'עקראם עפיף',       'number': 19, 'position': 'FWD', 'club': 'אל-סד'},
            {'name': 'ג׳אסם ג׳אבר',      'number': 17, 'position': 'MID', 'club': 'אל-ריאן'},
            {'name': 'יוסוף איימן',      'number': 21, 'position': 'FWD', 'club': 'אל-דוחאיל'},
        ],
    },

    'swi': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'יאן זומר',          'number': 1,  'position': 'GK',  'club': 'אינטר'},
            {'name': 'סילבאן ווידמר',    'number': 2,  'position': 'DEF', 'club': 'מיינץ'},
            {'name': 'מנואל אקאנג׳י',    'number': 5,  'position': 'DEF', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'ניקו אלקהו',       'number': 6,  'position': 'DEF', 'club': 'נייר'},
            {'name': 'ריקרדו רודריגז',   'number': 13, 'position': 'DEF', 'club': 'טורינו'},
            {'name': 'ראמו ברילה',       'number': 10, 'position': 'MID', 'club': 'באיירן מינכן'},
            {'name': 'גרניט ז׳אקה',      'number': 8,  'position': 'MID', 'club': 'בארסלונה'},
            {'name': 'ד׳אן נדויה',       'number': 23, 'position': 'MID', 'club': 'שטוטגרט'},
            {'name': 'ז׳רדן שאקירי',     'number': 7,  'position': 'FWD', 'club': 'שיקגו פייר'},
            {'name': 'נוה אואפים-סטי',   'number': 9,  'position': 'FWD', 'club': 'מנצ׳סטר סיטי'},
            {'name': 'רובן וארגאס',      'number': 11, 'position': 'FWD', 'club': 'אוגסבורג'},
        ],
        'bench': [
            {'name': 'גרגורי קוביצ׳',   'number': 21, 'position': 'GK',  'club': 'שטוטגרט'},
            {'name': 'פביאן שאר',        'number': 4,  'position': 'DEF', 'club': 'ניוקאסל'},
            {'name': 'קווין מבאבו',      'number': 14, 'position': 'MID', 'club': 'לוזאן'},
            {'name': 'ברל אמבולו',       'number': 17, 'position': 'FWD', 'club': 'מונאקו'},
            {'name': 'הרי סוטר',         'number': 19, 'position': 'MID', 'club': 'פריבורג'},
        ],
    },

    # ── GROUP C ──────────────────────────────────────────────────────────────

    'bra': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'אדרסון',            'number': 1,  'position': 'GK',  'club': 'מנצ׳סטר סיטי'},
            {'name': 'דניילו',            'number': 2,  'position': 'DEF', 'club': 'יובנטוס'},
            {'name': 'מרקיניוס',          'number': 4,  'position': 'DEF', 'club': 'PSG'},
            {'name': 'גבריאל מגאלייש',   'number': 5,  'position': 'DEF', 'club': 'ארסנל'},
            {'name': 'ג׳ורלאם',           'number': 6,  'position': 'DEF', 'club': 'אינטר'},
            {'name': 'ברונו גימאריש',     'number': 8,  'position': 'MID', 'club': 'ניוקאסל'},
            {'name': 'קאסמירו',           'number': 5,  'position': 'MID', 'club': 'מנצ׳סטר יונייטד'},
            {'name': 'לוקאס פקטה',        'number': 7,  'position': 'MID', 'club': 'ווסטהאם'},
            {'name': 'וינישיוס ז׳וניור',  'number': 11, 'position': 'FWD', 'club': 'ריאל מדריד'},
            {'name': 'רודריגו',           'number': 10, 'position': 'FWD', 'club': 'ריאל מדריד'},
            {'name': 'גבריאל מרטינלי',   'number': 11, 'position': 'FWD', 'club': 'ארסנל'},
        ],
        'bench': [
            {'name': 'וושינגטון',         'number': 23, 'position': 'GK',  'club': 'פאלמיירס'},
            {'name': 'אנדר מילילאו',      'number': 13, 'position': 'GK',  'club': 'צ׳לסי'},
            {'name': 'אנדריי סנטוס',      'number': 16, 'position': 'MID', 'club': 'צ׳לסי'},
            {'name': 'אנדריק',            'number': 9,  'position': 'FWD', 'club': 'ריאל מדריד'},
            {'name': 'גבריאל ברבוסה',    'number': 9,  'position': 'FWD', 'club': 'פלמנגו'},
            {'name': 'לוקאס ברבוסה',     'number': 19, 'position': 'FWD', 'club': 'פורטו'},
        ],
    },

    'mar': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'יאסין בונו',        'number': 1,  'position': 'GK',  'club': 'אל-הילאל'},
            {'name': 'אכרף חאקימי',       'number': 2,  'position': 'DEF', 'club': 'PSG'},
            {'name': 'נאיף אגואארד',      'number': 5,  'position': 'DEF', 'club': 'ברייטון'},
            {'name': 'רומאן סאיס',        'number': 6,  'position': 'DEF', 'club': 'אל-קדסייה'},
            {'name': 'נוסיר מזראווי',     'number': 3,  'position': 'DEF', 'club': 'בארסלונה'},
            {'name': 'סופיין אמרבאט',     'number': 4,  'position': 'MID', 'club': 'פיורנטינה'},
            {'name': 'עזדין אונאחי',      'number': 8,  'position': 'MID', 'club': 'מרסיי'},
            {'name': 'סלים אמאלה',        'number': 7,  'position': 'MID', 'club': 'ניוקאסל'},
            {'name': 'האקים זיאש',        'number': 10, 'position': 'FWD', 'club': 'גלטסריי'},
            {'name': 'יוסף אן-נסירי',    'number': 9,  'position': 'FWD', 'club': 'מגלאגה'},
            {'name': 'סופיין בופאל',      'number': 11, 'position': 'FWD', 'club': 'בורנמות׳'},
        ],
        'bench': [
            {'name': 'מונסיר מוחמד',      'number': 16, 'position': 'GK',  'club': 'ראסינג'},
            {'name': 'נבילה מלול',        'number': 15, 'position': 'DEF', 'club': 'זרגוזה'},
            {'name': 'אבדלחמיד סבירי',    'number': 17, 'position': 'MID', 'club': 'סטוק סיטי'},
            {'name': 'איליאס חאיר',       'number': 19, 'position': 'FWD', 'club': 'מידלסברה'},
            {'name': 'עאדל טעארבט',       'number': 14, 'position': 'MID', 'club': 'שפילד יונייטד'},
        ],
    },

    'hai': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'ג׳וני גייאר',       'number': 1,  'position': 'GK',  'club': 'מונטריאל'},
            {'name': 'קלאדנס בנגאה',      'number': 2,  'position': 'DEF', 'club': 'ניו-יורק RB'},
            {'name': 'סטיבנסון נאנג׳ו',  'number': 5,  'position': 'DEF', 'club': 'ניאגרה'},
            {'name': 'פיליפ ז׳אן-לואי',  'number': 6,  'position': 'DEF', 'club': 'גזנטפ'},
            {'name': 'ז׳ין-ז׳אק פייר',   'number': 3,  'position': 'DEF', 'club': 'FC מונטריאל'},
            {'name': 'נחמי ז׳וסף',        'number': 8,  'position': 'MID', 'club': 'מיאמי FC'},
            {'name': 'מטיאס ז׳ן',         'number': 4,  'position': 'MID', 'club': 'פורט-או-פרנס'},
            {'name': 'גלאדסטון ז׳ין',     'number': 7,  'position': 'MID', 'club': 'FC מונטריאל'},
            {'name': 'קנדל ווטסון',       'number': 11, 'position': 'MID', 'club': 'ניו-אינגלנד'},
            {'name': 'ניקולאס אסלוט',     'number': 10, 'position': 'FWD', 'club': 'KV אוסטנד'},
            {'name': 'ז׳ן בפטיסט',        'number': 9,  'position': 'FWD', 'club': 'ג׳מייקה'},
        ],
        'bench': [
            {'name': 'פול ז׳ן',           'number': 13, 'position': 'GK',  'club': 'קאפ-איטיין'},
            {'name': 'מנואל ברטראן',      'number': 15, 'position': 'DEF', 'club': 'קאנאדה'},
            {'name': 'ז׳וצ׳לאן ז׳אן',    'number': 17, 'position': 'MID', 'club': 'ניאגרה'},
            {'name': 'ד׳אנה אדריאן',      'number': 19, 'position': 'FWD', 'club': 'האיטי לאונס'},
            {'name': 'פייר גסטאב',        'number': 20, 'position': 'FWD', 'club': 'ניו-יורק סיטי'},
        ],
    },

    'sco': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'אנגוס גאן',         'number': 1,  'position': 'GK',  'club': 'נורוויץ׳'},
            {'name': 'אנתוני ראלסטון',   'number': 2,  'position': 'DEF', 'club': 'סלטיק'},
            {'name': 'גרנט הנלי',         'number': 5,  'position': 'DEF', 'club': 'נורוויץ׳'},
            {'name': 'סקוט מקקנה',       'number': 6,  'position': 'DEF', 'club': 'אמסטרדם'},
            {'name': 'אנדי רוברטסון',    'number': 3,  'position': 'DEF', 'club': 'ליברפול'},
            {'name': 'קאלום מקגרגור',    'number': 8,  'position': 'MID', 'club': 'סלטיק'},
            {'name': 'ביליאם ג׳ילמור',   'number': 4,  'position': 'MID', 'club': 'ברייטון'},
            {'name': 'סקוט מקטומיניי',   'number': 6,  'position': 'MID', 'club': 'נאפולי'},
            {'name': 'ריאן קריסטי',       'number': 7,  'position': 'FWD', 'club': 'בורנמות׳'},
            {'name': 'לורי קלוור',        'number': 11, 'position': 'FWD', 'club': 'אוורטון'},
            {'name': 'קירן טיר',          'number': 9,  'position': 'FWD', 'club': 'האמפדן'},
        ],
        'bench': [
            {'name': 'קרייג גורדון',      'number': 13, 'position': 'GK',  'club': 'הארטס'},
            {'name': 'ג׳ק הנדרי',         'number': 14, 'position': 'DEF', 'club': 'קוון'},
            {'name': 'ג׳ון מקגין',        'number': 7,  'position': 'MID', 'club': 'אסטון וילה'},
            {'name': 'ריאן פורסית׳',      'number': 10, 'position': 'FWD', 'club': 'נוטינגהם פורסט'},
            {'name': 'לורן ניל',          'number': 21, 'position': 'MID', 'club': 'עבדין'},
        ],
    },

    # ── GROUP D ──────────────────────────────────────────────────────────────

    'usa': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'מאט טרנר',          'number': 1,  'position': 'GK',  'club': 'נוטינגהם פורסט'},
            {'name': 'סרג׳יניו דסט',      'number': 2,  'position': 'DEF', 'club': 'PSV'},
            {'name': 'ווקר זימרמן',       'number': 5,  'position': 'DEF', 'club': 'נאשוויל'},
            {'name': 'מייילס רובינסון',   'number': 6,  'position': 'DEF', 'club': 'אטלנטה יונייטד'},
            {'name': 'אנטוניי רובינסון',  'number': 3,  'position': 'DEF', 'club': 'פולהאם'},
            {'name': 'וסטון מקני',        'number': 8,  'position': 'MID', 'club': 'יובנטוס'},
            {'name': 'טיילר אדאמס',       'number': 4,  'position': 'MID', 'club': 'בורנמות׳'},
            {'name': 'יובני ריאן',        'number': 7,  'position': 'MID', 'club': 'ריאל סוסיאדד'},
            {'name': 'כריסטיאן פולישיץ׳', 'number': 10, 'position': 'FWD', 'club': 'AC מילאן'},
            {'name': 'ברנדן אראוחו',      'number': 9,  'position': 'FWD', 'club': 'FC דאלאס'},
            {'name': 'טימות׳י וה',        'number': 11, 'position': 'FWD', 'club': 'פריז סן-ז׳רמן'},
        ],
        'bench': [
            {'name': 'אטן נוואנרי',       'number': 13, 'position': 'GK',  'club': 'ניוקאסל'},
            {'name': 'ג׳ו שקיאן',         'number': 15, 'position': 'DEF', 'club': 'VfB שטוטגרט'},
            {'name': 'לוקוס דיגנאן',      'number': 17, 'position': 'MID', 'club': 'ריד בול'},
            {'name': 'פולגה מוסה',        'number': 20, 'position': 'FWD', 'club': 'ניו-יורק RB'},
            {'name': 'רייק ריי',           'number': 23, 'position': 'FWD', 'club': 'לוס אנג׳לס'},
        ],
    },

    'par': {
        'formation': '4-4-2',
        'starters': [
            {'name': 'גתאנו ספרטה',       'number': 1,  'position': 'GK',  'club': 'ולייבולטון'},
            {'name': 'איבאן ד׳ישה',       'number': 2,  'position': 'DEF', 'club': 'נאסיונל'},
            {'name': 'פאביאן בלס',        'number': 5,  'position': 'DEF', 'club': 'ג׳נרלוס'},
            {'name': 'ז׳וניור אלונסו',    'number': 6,  'position': 'DEF', 'club': 'בניקה'},
            {'name': 'קומינס',            'number': 3,  'position': 'DEF', 'club': 'גרמיו'},
            {'name': 'מיגל אלמירון',      'number': 8,  'position': 'MID', 'club': 'ניוקאסל'},
            {'name': 'מתיאס וילאסנטי',   'number': 16, 'position': 'MID', 'club': 'ינג׳ פלורי'},
            {'name': 'ג׳וס מרטינס',       'number': 7,  'position': 'MID', 'club': 'ספורטינג'},
            {'name': 'אנחל רומרו',        'number': 11, 'position': 'MID', 'club': 'אינטר'},
            {'name': 'אנטואן דה לוכה',   'number': 10, 'position': 'FWD', 'club': 'אסנאל'},
            {'name': 'גוסטאבו גומז',      'number': 9,  'position': 'FWD', 'club': 'פאלמיירס'},
        ],
        'bench': [
            {'name': 'אנטוניו סילבה',     'number': 12, 'position': 'GK',  'club': 'נאסיונל'},
            {'name': 'ברונו ואלנסואלה',   'number': 4,  'position': 'DEF', 'club': 'טראבזונספור'},
            {'name': 'ריצ׳ארד סנצ׳ס',    'number': 17, 'position': 'MID', 'club': 'פנמה'},
            {'name': 'חוליאן בנייגס',     'number': 19, 'position': 'MID', 'club': 'ינג׳ פלורי'},
            {'name': 'רוברטו מוריניגו',   'number': 20, 'position': 'FWD', 'club': 'גרנדה'},
        ],
    },

    'aus': {
        'formation': '4-3-3',
        'starters': [
            {'name': 'מתיאס ריאן',        'number': 1,  'position': 'GK',  'club': 'ברייטון'},
            {'name': 'מתיאס לקי',         'number': 2,  'position': 'DEF', 'club': 'פולהאם'},
            {'name': 'הארי סאוטר',        'number': 5,  'position': 'DEF', 'club': 'שפילד יונייטד'},
            {'name': 'קאי רוסמן',         'number': 6,  'position': 'DEF', 'club': 'ווסטהאם'},
            {'name': 'אורן בורנה',         'number': 3,  'position': 'DEF', 'club': 'ואנקובר'},
            {'name': 'ריילי מקגרי',       'number': 8,  'position': 'MID', 'club': 'FC דאלאס'},
            {'name': 'אייידן בוגדן',      'number': 4,  'position': 'MID', 'club': 'סאות׳המפטון'},
            {'name': 'ג׳קסון ארנברג',     'number': 7,  'position': 'MID', 'club': 'NEC ניימחן'},
            {'name': 'קאמרון דבסניקה',    'number': 11, 'position': 'FWD', 'club': 'NEC ניימחן'},
            {'name': 'מיצ׳ל דיוק',        'number': 9,  'position': 'FWD', 'club': 'FC דאלאס'},
            {'name': 'מרטין בויל',        'number': 10, 'position': 'FWD', 'club': 'היברניאן'},
        ],
        'bench': [
            {'name': 'דני ווקי',          'number': 13, 'position': 'GK',  'club': 'מלבורן ויקטורי'},
            {'name': 'טום רודיץ׳',        'number': 14, 'position': 'DEF', 'club': 'מלבורן סיטי'},
            {'name': 'קוננור מטאגארט',    'number': 17, 'position': 'MID', 'club': 'מלבורן סיטי'},
            {'name': 'בנג׳מין אולד',      'number': 19, 'position': 'FWD', 'club': 'הרטה'},
            {'name': 'ניק ד׳אגוסטינו',   'number': 20, 'position': 'FWD', 'club': 'פולהאם'},
        ],
    },

    'tur': {
        'formation': '4-2-3-1',
        'starters': [
            {'name': 'אלטאי בייינדיר',   'number': 1,  'position': 'GK',  'club': 'מנצ׳סטר יונייטד'},
            {'name': 'מהמד ז׳נגיז אונדר','number': 2,  'position': 'DEF', 'club': 'פנרבהצ׳ה'},
            {'name': 'מריח דמיראל',       'number': 5,  'position': 'DEF', 'club': 'אל-קדסייה'},
            {'name': 'עאגה אקאייאדין',   'number': 6,  'position': 'DEF', 'club': 'גלטסריי'},
            {'name': 'פרהאן צ׳אלחאנוגלו','number': 3,  'position': 'DEF', 'club': 'בשיקטאש'},
            {'name': 'סלחנו אוגדז',       'number': 8,  'position': 'MID', 'club': 'גלטסריי'},
            {'name': 'האקאן צ׳אלחאנוגלו','number': 10, 'position': 'MID', 'club': 'אינטר'},
            {'name': 'מחמד אוגוז',        'number': 17, 'position': 'MID', 'club': 'גלטסריי'},
            {'name': 'קייס אקסוי',        'number': 11, 'position': 'MID', 'club': 'ברלין'},
            {'name': 'ארדם בצ׳יר',        'number': 7,  'position': 'MID', 'club': 'פנרבהצ׳ה'},
            {'name': 'בוראק ילמאז',       'number': 9,  'position': 'FWD', 'club': 'טראבזונספור'},
        ],
        'bench': [
            {'name': 'מרט גונוק',         'number': 23, 'position': 'GK',  'club': 'בשיקטאש'},
            {'name': 'פאגה יאקינוג׳לו',  'number': 4,  'position': 'DEF', 'club': 'פנרבהצ׳ה'},
            {'name': 'יוסוף יאזיצ׳י',    'number': 14, 'position': 'MID', 'club': 'גלטסריי'},
            {'name': 'אמרה דמיר',         'number': 19, 'position': 'FWD', 'club': 'גלטסריי'},
            {'name': 'ב׳רול ז׳נגיז',      'number': 21, 'position': 'FWD', 'club': 'בשיקטאש'},
        ],
    },
}
