import type { WorldCupMatch, WorldCupPlayerStat, WorldCupStanding, WorldCupTeam, WorldCupTeamDetail, WorldCupVenue } from './types';

export const WORLD_CUP_START_ISO = '2026-06-11T22:00:00.000Z';

export const teams: Record<string, WorldCupTeam> = {
  mex: { id: 'mex', nameHe: 'מקסיקו', nameEn: 'Mexico', flag: '🇲🇽' },
  rsa: { id: 'rsa', nameHe: 'דרום אפריקה', nameEn: 'South Africa', flag: '🇿🇦' },
  can: { id: 'can', nameHe: 'קנדה', nameEn: 'Canada', flag: '🇨🇦' },
  qat: { id: 'qat', nameHe: 'קטאר', nameEn: 'Qatar', flag: '🇶🇦' },
  usa: { id: 'usa', nameHe: 'ארצות הברית', nameEn: 'United States', flag: '🇺🇸' },
  par: { id: 'par', nameHe: 'פרגוואי', nameEn: 'Paraguay', flag: '🇵🇾' },
  bra: { id: 'bra', nameHe: 'ברזיל', nameEn: 'Brazil', flag: '🇧🇷' },
  mar: { id: 'mar', nameHe: 'מרוקו', nameEn: 'Morocco', flag: '🇲🇦' },
  arg: { id: 'arg', nameHe: 'ארגנטינה', nameEn: 'Argentina', flag: '🇦🇷' },
  alg: { id: 'alg', nameHe: 'אלג׳יריה', nameEn: 'Algeria', flag: '🇩🇿' },
  ger: { id: 'ger', nameHe: 'גרמניה', nameEn: 'Germany', flag: '🇩🇪' },
  nzl: { id: 'nzl', nameHe: 'ניו זילנד', nameEn: 'New Zealand', flag: '🇳🇿' },
  eng: { id: 'eng', nameHe: 'אנגליה', nameEn: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  cro: { id: 'cro', nameHe: 'קרואטיה', nameEn: 'Croatia', flag: '🇭🇷' },
  esp: { id: 'esp', nameHe: 'ספרד', nameEn: 'Spain', flag: '🇪🇸' },
  jpn: { id: 'jpn', nameHe: 'יפן', nameEn: 'Japan', flag: '🇯🇵' },
  tbd: { id: 'tbd', nameHe: 'ייקבע בהמשך', nameEn: 'TBD', flag: '🏳️' },
};

export const venues: WorldCupVenue[] = [
  { id: 'mexico-city', nameHe: 'אצטדיון מקסיקו סיטי', nameEn: 'Mexico City Stadium', cityHe: 'מקסיקו סיטי', cityEn: 'Mexico City', countryHe: 'מקסיקו', capacity: 83000, latitude: 19.3029, longitude: -99.1505, imageUrl: 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=1200&q=80', factHe: 'האצטדיון היחיד שיארח משחק פתיחה שלישי במונדיאל.' },
  { id: 'guadalajara', nameHe: 'אצטדיון גוודלחרה', nameEn: 'Guadalajara Stadium', cityHe: 'גוודלחרה', cityEn: 'Guadalajara', countryHe: 'מקסיקו', capacity: 48000, latitude: 20.6818, longitude: -103.4621, imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80', factHe: 'בית מודרני עם גג טבעתי שמבליט את קו הרקיע המקומי.' },
  { id: 'monterrey', nameHe: 'אצטדיון מונטריי', nameEn: 'Monterrey Stadium', cityHe: 'מונטריי', cityEn: 'Monterrey', countryHe: 'מקסיקו', capacity: 53500, latitude: 25.6689, longitude: -100.2449, imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80', factHe: 'חזית זכוכית דרמטית מול רכסי ההרים של נואבו לאון.' },
  { id: 'toronto', nameHe: 'אצטדיון טורונטו', nameEn: 'Toronto Stadium', cityHe: 'טורונטו', cityEn: 'Toronto', countryHe: 'קנדה', capacity: 45500, latitude: 43.6328, longitude: -79.4186, imageUrl: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80', factHe: 'אצטדיון עירוני קומפקטי על שפת אגם אונטריו.' },
  { id: 'vancouver', nameHe: 'אצטדיון ונקובר', nameEn: 'Vancouver Stadium', cityHe: 'ונקובר', cityEn: 'Vancouver', countryHe: 'קנדה', capacity: 54500, latitude: 49.2768, longitude: -123.1119, imageUrl: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1200&q=80', factHe: 'גג כבלים ייחודי שנראה כמו מפרש מעל הדאונטאון.' },
  { id: 'atlanta', nameHe: 'אצטדיון אטלנטה', nameEn: 'Atlanta Stadium', cityHe: 'אטלנטה', cityEn: 'Atlanta', countryHe: 'ארצות הברית', capacity: 71000, latitude: 33.7554, longitude: -84.4008, imageUrl: 'https://images.unsplash.com/photo-1505842465776-3c42f29ddca4?auto=format&fit=crop&w=1200&q=80', factHe: 'גג נפתח בהשראת עדשת מצלמה ומסך הילה עצום.' },
  { id: 'boston', nameHe: 'אצטדיון בוסטון', nameEn: 'Boston Stadium', cityHe: 'בוסטון', cityEn: 'Boston', countryHe: 'ארצות הברית', capacity: 65800, latitude: 42.0909, longitude: -71.2643, imageUrl: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?auto=format&fit=crop&w=1200&q=80', factHe: 'אצטדיון פתוח עם אווירת פוטבול קלאסית בניו אינגלנד.' },
  { id: 'dallas', nameHe: 'אצטדיון דאלאס', nameEn: 'Dallas Stadium', cityHe: 'דאלאס', cityEn: 'Dallas', countryHe: 'ארצות הברית', capacity: 94000, latitude: 32.7473, longitude: -97.0945, imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80', factHe: 'אחד האצטדיונים הגדולים בטורניר, עם קשתות פלדה עצומות.' },
  { id: 'houston', nameHe: 'אצטדיון יוסטון', nameEn: 'Houston Stadium', cityHe: 'יוסטון', cityEn: 'Houston', countryHe: 'ארצות הברית', capacity: 72200, latitude: 29.6847, longitude: -95.4107, imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1200&q=80', factHe: 'גג נפתח שמאפשר התאמה לחום ולקצב המשחקים.' },
  { id: 'kansas-city', nameHe: 'אצטדיון קנזס סיטי', nameEn: 'Kansas City Stadium', cityHe: 'קנזס סיטי', cityEn: 'Kansas City', countryHe: 'ארצות הברית', capacity: 76400, latitude: 39.049, longitude: -94.4839, imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80', factHe: 'ידוע באקוסטיקה חזקה במיוחד וביציעים תלולים.' },
  { id: 'los-angeles', nameHe: 'אצטדיון לוס אנג׳לס', nameEn: 'Los Angeles Stadium', cityHe: 'לוס אנג׳לס', cityEn: 'Los Angeles', countryHe: 'ארצות הברית', capacity: 70240, latitude: 33.9535, longitude: -118.3392, imageUrl: 'https://images.unsplash.com/photo-1495257008495-441709c6d8ba?auto=format&fit=crop&w=1200&q=80', factHe: 'קומפלקס חדשני עם גג שקוף ורחבה עירונית ענקית.' },
  { id: 'miami', nameHe: 'אצטדיון מיאמי', nameEn: 'Miami Stadium', cityHe: 'מיאמי', cityEn: 'Miami', countryHe: 'ארצות הברית', capacity: 65300, latitude: 25.958, longitude: -80.2389, imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80', factHe: 'אצטדיון טרופי עם הצללה עמוקה סביב היציעים.' },
  { id: 'new-york-new-jersey', nameHe: 'אצטדיון ניו יורק ניו ג׳רזי', nameEn: 'New York New Jersey Stadium', cityHe: 'ניו יורק ניו ג׳רזי', cityEn: 'New York New Jersey', countryHe: 'ארצות הברית', capacity: 82500, latitude: 40.8135, longitude: -74.0745, imageUrl: 'https://images.unsplash.com/photo-1518604666860-9ed391f76460?auto=format&fit=crop&w=1200&q=80', factHe: 'יארח את גמר מונדיאל 2026 ב-19 ביולי.' },
  { id: 'philadelphia', nameHe: 'אצטדיון פילדלפיה', nameEn: 'Philadelphia Stadium', cityHe: 'פילדלפיה', cityEn: 'Philadelphia', countryHe: 'ארצות הברית', capacity: 69000, latitude: 39.9008, longitude: -75.1675, imageUrl: 'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80', factHe: 'נמצא בלב רובע הספורט ההיסטורי של העיר.' },
  { id: 'san-francisco-bay-area', nameHe: 'אצטדיון אזור מפרץ סן פרנסיסקו', nameEn: 'San Francisco Bay Area Stadium', cityHe: 'סן פרנסיסקו', cityEn: 'San Francisco Bay Area', countryHe: 'ארצות הברית', capacity: 68500, latitude: 37.403, longitude: -121.97, imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80', factHe: 'אצטדיון הייטק בסמוך לעמק הסיליקון.' },
  { id: 'seattle', nameHe: 'אצטדיון סיאטל', nameEn: 'Seattle Stadium', cityHe: 'סיאטל', cityEn: 'Seattle', countryHe: 'ארצות הברית', capacity: 69000, latitude: 47.5952, longitude: -122.3316, imageUrl: 'https://images.unsplash.com/photo-1517142089942-ba376ce32a2e?auto=format&fit=crop&w=1200&q=80', factHe: 'גג פתוח למחצה שמרכז את הרעש אל תוך המגרש.' },
];

export const fallbackMatches: WorldCupMatch[] = [
  { id: 'm1', matchNumber: 1, stage: 'group', group: 'A', homeTeam: teams.mex, awayTeam: teams.rsa, homeScore: null, awayScore: null, status: 'scheduled', kickoff: WORLD_CUP_START_ISO, venueId: 'mexico-city', broadcaster: 'kan11' },
  { id: 'm2', matchNumber: 2, stage: 'group', group: 'B', homeTeam: teams.can, awayTeam: teams.qat, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-06-12T00:00:00.000Z', venueId: 'toronto', broadcaster: 'kan11' },
  { id: 'm3', matchNumber: 3, stage: 'group', group: 'D', homeTeam: teams.usa, awayTeam: teams.par, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-06-13T02:00:00.000Z', venueId: 'los-angeles', broadcaster: 'kan11' },
  { id: 'm4', matchNumber: 4, stage: 'group', group: 'C', homeTeam: teams.bra, awayTeam: teams.mar, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-06-13T19:00:00.000Z', venueId: 'miami', broadcaster: 'kan11' },
  { id: 'm5', matchNumber: 5, stage: 'group', group: 'E', homeTeam: teams.arg, awayTeam: teams.alg, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-06-14T00:00:00.000Z', venueId: 'new-york-new-jersey', broadcaster: 'kan11' },
  { id: 'm6', matchNumber: 6, stage: 'group', group: 'F', homeTeam: teams.ger, awayTeam: teams.nzl, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-06-14T22:00:00.000Z', venueId: 'dallas', broadcaster: 'kan11' },
  { id: 'm7', matchNumber: 7, stage: 'group', group: 'G', homeTeam: teams.eng, awayTeam: teams.cro, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-06-15T19:00:00.000Z', venueId: 'seattle', broadcaster: 'kan11' },
  { id: 'm8', matchNumber: 8, stage: 'group', group: 'H', homeTeam: teams.esp, awayTeam: teams.jpn, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-06-15T22:00:00.000Z', venueId: 'vancouver', broadcaster: 'kan11' },
  { id: 'm104', matchNumber: 104, stage: 'final', homeTeam: teams.tbd, awayTeam: teams.tbd, homeScore: null, awayScore: null, status: 'scheduled', kickoff: '2026-07-19T19:00:00.000Z', venueId: 'new-york-new-jersey', broadcaster: 'kan11' },
];

export const fallbackStandings: WorldCupStanding[] = ['A', 'B', 'C', 'D'].flatMap((group) => {
  const groupTeams = group === 'A' ? [teams.mex, teams.rsa, teams.tbd, teams.tbd]
    : group === 'B' ? [teams.can, teams.qat, teams.tbd, teams.tbd]
      : group === 'C' ? [teams.bra, teams.mar, teams.tbd, teams.tbd]
        : [teams.usa, teams.par, teams.tbd, teams.tbd];
  return groupTeams.map((team) => ({
    group,
    team,
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    points: 0,
  }));
});

export const teamDetails: WorldCupTeamDetail[] = [
  /* ─── CONMEBOL (6) ─── */
  {
    id: 'arg', nameHe: 'ארגנטינה', nameEn: 'Argentina', flag: '🇦🇷',
    confederation: 'CONMEBOL', coachHe: 'ליאונל סקלוני', coachEn: 'Lionel Scaloni',
    fifaRanking: 1, worldCupTitles: 3, bestResult: 'אלוף (1978, 1986, 2022)',
    group: 'E',
    squad: [
      { name: 'אמיליאנו מרטינס', number: 23, position: 'GK', club: 'אסטון וילה' },
      { name: 'ניקולאס אוטמנדי', number: 19, position: 'DEF', club: 'בנפיקה' },
      { name: 'כריסטיאן רומרו', number: 13, position: 'DEF', club: 'טוטנהאם' },
      { name: 'מרקוס אקוניה', number: 8, position: 'DEF', club: 'סוויינסי' },
      { name: 'רודריגו דה פול', number: 7, position: 'MID', club: 'אטלטיקו מדריד' },
      { name: 'אנצו פרנאנדס', number: 24, position: 'MID', club: 'צ׳לסי' },
      { name: 'אלכסיס מאק אליסטר', number: 20, position: 'MID', club: 'ליברפול' },
      { name: 'ליאונל מסי', number: 10, position: 'FWD', club: 'אינטר מיאמי', caps: 187, goals: 109 },
      { name: 'חוליאן אלבארס', number: 9, position: 'FWD', club: 'אטלטיקו מדריד' },
      { name: 'לאוטרו מרטינס', number: 22, position: 'FWD', club: 'אינטר מילאן' },
      { name: 'אנחל די מריה', number: 11, position: 'FWD', club: 'פנאתינייקוס' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'אלוף', notes: 'גמר מול צרפת, ניצחון בפנדלים' },
      { year: 2018, host: 'רוסיה', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: 'גמר', notes: 'הפסד לגרמניה 0-1' },
      { year: 2010, host: 'דרום אפריקה', stage: 'רבע גמר' },
      { year: 2006, host: 'גרמניה', stage: 'רבע גמר' },
    ],
  },
  {
    id: 'bra', nameHe: 'ברזיל', nameEn: 'Brazil', flag: '🇧🇷',
    confederation: 'CONMEBOL', coachHe: 'דורי', coachEn: 'Dorival Jr.',
    fifaRanking: 5, worldCupTitles: 5, bestResult: 'אלוף (1958, 1962, 1970, 1994, 2002)',
    group: 'C',
    squad: [
      { name: 'אלאסון', number: 1, position: 'GK', club: 'צ׳לסי' },
      { name: 'דניאלו', number: 2, position: 'DEF', club: 'יובנטוס' },
      { name: 'מרקיניוס', number: 3, position: 'DEF', club: 'פריז סן ז׳רמן' },
      { name: 'ויניסיוס ז׳וניור', number: 7, position: 'FWD', club: 'ריאל מדריד', caps: 55, goals: 25 },
      { name: 'רודריגו', number: 19, position: 'FWD', club: 'ריאל מדריד' },
      { name: 'לוקס פקטה', number: 10, position: 'MID', club: 'ווסטהאם' },
      { name: 'ברונו גימאראש', number: 5, position: 'MID', club: 'ניוקאסל' },
      { name: 'ראפינייה', number: 11, position: 'FWD', club: 'ברצלונה' },
      { name: 'אנדריק', number: 9, position: 'FWD', club: 'ריאל מדריד' },
      { name: 'ריאליסון', number: 18, position: 'FWD', club: 'טוטנהאם' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'רבע גמר', notes: 'הפסד לקרואטיה בפנדלים' },
      { year: 2018, host: 'רוסיה', stage: 'רבע גמר' },
      { year: 2014, host: 'ברזיל', stage: 'מקום רביעי', notes: 'הפסד 1-7 לגרמניה' },
      { year: 2010, host: 'דרום אפריקה', stage: 'רבע גמר' },
      { year: 2006, host: 'גרמניה', stage: 'רבע גמר' },
      { year: 2002, host: 'יפן/קוריאה', stage: 'אלוף' },
    ],
  },
  {
    id: 'fra', nameHe: 'צרפת', nameEn: 'France', flag: '🇫🇷',
    confederation: 'UEFA', coachHe: 'דידייה דשאן', coachEn: 'Didier Deschamps',
    fifaRanking: 2, worldCupTitles: 2, bestResult: 'אלוף (1998, 2018)',
    group: 'D',
    squad: [
      { name: 'מייק מניאן', number: 1, position: 'GK', club: 'ריאל מדריד' },
      { name: 'תיאו הרנאנדס', number: 22, position: 'DEF', club: 'AC מילאן' },
      { name: 'ווילים סאליבה', number: 5, position: 'DEF', club: 'ארסנל' },
      { name: 'קיליאן אמבאפה', number: 10, position: 'FWD', club: 'ריאל מדריד', caps: 85, goals: 48 },
      { name: 'אוסמאן דמבלה', number: 11, position: 'FWD', club: 'פריז סן ז׳רמן' },
      { name: 'אנטואן גריזמן', number: 7, position: 'FWD', club: 'אטלטיקו מדריד' },
      { name: 'אדריאן ראביו', number: 14, position: 'MID', club: 'יובנטוס' },
      { name: 'טורם', number: 8, position: 'MID', club: 'אינטר מילאן' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'גמר', notes: 'הפסד לארגנטינה בפנדלים' },
      { year: 2018, host: 'רוסיה', stage: 'אלוף' },
      { year: 2014, host: 'ברזיל', stage: 'רבע גמר' },
      { year: 2010, host: 'דרום אפריקה', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: 'גמר' },
    ],
  },
  {
    id: 'eng', nameHe: 'אנגליה', nameEn: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    confederation: 'UEFA', coachHe: 'לי קארסלי', coachEn: 'Lee Carsley',
    fifaRanking: 4, worldCupTitles: 1, bestResult: 'אלוף (1966)',
    group: 'G',
    squad: [
      { name: 'ג׳ורדן פיקפורד', number: 1, position: 'GK', club: 'אברטון' },
      { name: 'קייל ווקר', number: 2, position: 'DEF', club: 'מנצ׳סטר סיטי' },
      { name: 'מארק גהי', number: 5, position: 'DEF', club: 'קריסטל פאלאס' },
      { name: 'ג׳וד בלינגהאם', number: 10, position: 'MID', club: 'ריאל מדריד', caps: 37, goals: 12 },
      { name: 'ברקלי', number: 8, position: 'MID', club: 'ליברפול' },
      { name: 'הארי קיין', number: 9, position: 'FWD', club: 'באיירן מינכן', caps: 97, goals: 68 },
      { name: 'פיל פודן', number: 20, position: 'FWD', club: 'מנצ׳סטר סיטי' },
      { name: 'בוקאיו סאקה', number: 17, position: 'FWD', club: 'ארסנל' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'רבע גמר' },
      { year: 2018, host: 'רוסיה', stage: 'חצי גמר' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: '16 האחרונות' },
      { year: 1966, host: 'אנגליה', stage: 'אלוף' },
    ],
  },
  {
    id: 'esp', nameHe: 'ספרד', nameEn: 'Spain', flag: '🇪🇸',
    confederation: 'UEFA', coachHe: 'לואיס דה לה פואנטה', coachEn: 'Luis de la Fuente',
    fifaRanking: 3, worldCupTitles: 1, bestResult: 'אלוף (2010)',
    group: 'H',
    squad: [
      { name: 'אונאי סימון', number: 1, position: 'GK', club: 'אתלטיק בילבאו' },
      { name: 'דאני קארבחאל', number: 2, position: 'DEF', club: 'ריאל מדריד' },
      { name: 'אורי מינה', number: 4, position: 'DEF', club: 'ויארל' },
      { name: 'פדרי', number: 8, position: 'MID', club: 'ברצלונה' },
      { name: 'רודרי', number: 16, position: 'MID', club: 'מנצ׳סטר סיטי' },
      { name: 'פאביאן רואיס', number: 6, position: 'MID', club: 'פריז סן ז׳רמן' },
      { name: 'לאמין יאמאל', number: 19, position: 'FWD', club: 'ברצלונה' },
      { name: 'ניקו ווילאמס', number: 17, position: 'FWD', club: 'אתלטיק בילבאו' },
      { name: 'מוראטה', number: 9, position: 'FWD', club: 'AC מילאן' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'רבע גמר' },
      { year: 2018, host: 'רוסיה', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: 'אלוף' },
      { year: 2006, host: 'גרמניה', stage: '16 האחרונות' },
    ],
  },
  {
    id: 'ger', nameHe: 'גרמניה', nameEn: 'Germany', flag: '🇩🇪',
    confederation: 'UEFA', coachHe: 'יוליאן נגלסמן', coachEn: 'Julian Nagelsmann',
    fifaRanking: 13, worldCupTitles: 4, bestResult: 'אלוף (1954, 1974, 1990, 2014)',
    group: 'F',
    squad: [
      { name: 'מנואל נויאר', number: 1, position: 'GK', club: 'באיירן מינכן' },
      { name: 'יושוע קימיך', number: 6, position: 'DEF', club: 'באיירן מינכן' },
      { name: 'אנטוניו רודיגר', number: 5, position: 'DEF', club: 'ריאל מדריד' },
      { name: 'ת׳ורגן קרוס', number: 8, position: 'MID', club: 'ריאל מדריד' },
      { name: 'יאמאל מוסיאלה', number: 10, position: 'FWD', club: 'באיירן מינכן' },
      { name: 'פלוריאן וירץ', number: 7, position: 'FWD', club: 'באיירן מינכן' },
      { name: 'קאי הוורץ', number: 11, position: 'FWD', club: 'ארסנל' },
      { name: 'ניקלאס פולקרוג', number: 9, position: 'FWD', club: 'ווסטהאם' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים' },
      { year: 2014, host: 'ברזיל', stage: 'אלוף' },
      { year: 2010, host: 'דרום אפריקה', stage: 'מקום שלישי' },
      { year: 2006, host: 'גרמניה', stage: 'מקום שלישי' },
    ],
  },
  {
    id: 'por', nameHe: 'פורטוגל', nameEn: 'Portugal', flag: '🇵🇹',
    confederation: 'UEFA', coachHe: 'רוברטו מרטינז', coachEn: 'Roberto Martínez',
    fifaRanking: 6, worldCupTitles: 0, bestResult: 'מקום שלישי (1966)',
    group: 'A',
    squad: [
      { name: 'דיוגו קוסטה', number: 1, position: 'GK', club: 'פורטו' },
      { name: 'ז׳ואאו קנסלו', number: 20, position: 'DEF', club: 'ברצלונה' },
      { name: 'ז׳וניור פירמינו', number: 3, position: 'DEF', club: 'אל קדסייה' },
      { name: 'קריסטיאנו רונאלדו', number: 7, position: 'FWD', club: 'אל נאסר', caps: 215, goals: 136 },
      { name: 'ברונו פרנאנדס', number: 8, position: 'MID', club: 'מנצ׳סטר יונייטד' },
      { name: 'ז׳וניור פלקס', number: 11, position: 'FWD', club: 'ברצלונה' },
      { name: 'רפאל לאאו', number: 10, position: 'FWD', club: 'AC מילאן' },
      { name: 'ג׳ואאו פליקס', number: 9, position: 'FWD', club: 'AC מילאן' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'רבע גמר' },
      { year: 2018, host: 'רוסיה', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: 'רבע גמר' },
      { year: 2006, host: 'גרמניה', stage: 'מקום רביעי' },
    ],
  },
  {
    id: 'ned', nameHe: 'הולנד', nameEn: 'Netherlands', flag: '🇳🇱',
    confederation: 'UEFA', coachHe: 'רונלד קואמן', coachEn: 'Ronald Koeman',
    fifaRanking: 7, worldCupTitles: 0, bestResult: 'גמר (1974, 1978, 2010)',
    group: 'B',
    squad: [
      { name: 'ברט פרברוגן', number: 1, position: 'GK', club: 'מנצ׳סטר סיטי' },
      { name: 'דנצל דומפריס', number: 22, position: 'DEF', club: 'אינטר מילאן' },
      { name: 'פירגיל ואן דייק', number: 4, position: 'DEF', club: 'ליברפול', caps: 70, goals: 8 },
      { name: 'קוויין ז׳ורגנסן', number: 5, position: 'DEF', club: 'פיורנטינה' },
      { name: 'טיג׳אני ריינדרס', number: 8, position: 'MID', club: 'AC מילאן' },
      { name: 'קופי קוקו', number: 7, position: 'MID', club: 'פנרבחה' },
      { name: 'קוי דומפריס', number: 11, position: 'FWD', club: 'ברנטפורד' },
      { name: 'ג׳ושוע זירקסי', number: 9, position: 'FWD', club: 'ברצלונה' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'רבע גמר' },
      { year: 2014, host: 'ברזיל', stage: 'מקום שלישי' },
      { year: 2010, host: 'דרום אפריקה', stage: 'גמר' },
      { year: 2006, host: 'גרמניה', stage: '16 האחרונות' },
    ],
  },
  {
    id: 'bel', nameHe: 'בלגיה', nameEn: 'Belgium', flag: '🇧🇪',
    confederation: 'UEFA', coachHe: 'דומניקו טדסקו', coachEn: 'Domenico Tedesco',
    fifaRanking: 3, worldCupTitles: 0, bestResult: 'מקום שלישי (2018)',
    group: 'C',
    squad: [
      { name: 'קובה קולר', number: 1, position: 'GK', club: 'גנט' },
      { name: 'תיאו הרמנס', number: 2, position: 'DEF', club: 'ליל' },
      { name: 'ינתה קאבוול', number: 3, position: 'DEF', club: 'סאות׳המפטון' },
      { name: 'ג׳ני מינגנסה', number: 8, position: 'MID', club: 'מנצ׳סטר יונייטד' },
      { name: 'יאנוס תיטה', number: 10, position: 'MID', club: 'מנצ׳סטר סיטי' },
      { name: 'לואיס אופנדה', number: 9, position: 'FWD', club: 'בורוסיה דורטמונד' },
      { name: 'לוקה נסיז', number: 11, position: 'FWD', club: 'בולוניה' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2018, host: 'רוסיה', stage: 'מקום שלישי' },
      { year: 2014, host: 'ברזיל', stage: 'רבע גמר' },
    ],
  },
  {
    id: 'usa', nameHe: 'ארצות הברית', nameEn: 'United States', flag: '🇺🇸',
    confederation: 'CONCACAF', coachHe: 'מורייסיו פוצ׳טינו', coachEn: 'Mauricio Pochettino',
    fifaRanking: 14, worldCupTitles: 0, bestResult: 'מקום שלישי (1930)',
    group: 'D',
    squad: [
      { name: 'מאט טרנר', number: 1, position: 'GK', club: 'קריסטל פאלאס' },
      { name: 'סרג׳ינו דסט', number: 2, position: 'DEF', club: 'PSV' },
      { name: 'טיי אדמס', number: 4, position: 'DEF', club: 'סאות׳המפטון' },
      { name: 'ויסטון מקני', number: 8, position: 'MID', club: 'יובנטוס' },
      { name: 'כריסטיאן פולישיץ׳', number: 10, position: 'MID', club: 'AC מילאן', caps: 65, goals: 26 },
      { name: 'יוסף מוואל', number: 11, position: 'FWD', club: 'מנצ׳סטר סיטי' },
      { name: 'טימות׳י וו', number: 17, position: 'FWD', club: 'באיירן מינכן' },
      { name: 'פולדי', number: 9, position: 'FWD', club: 'בולוניה' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: '16 האחרונות' },
      { year: 2010, host: 'דרום אפריקה', stage: '16 האחרונות' },
      { year: 2006, host: 'גרמניה', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'mex', nameHe: 'מקסיקו', nameEn: 'Mexico', flag: '🇲🇽',
    confederation: 'CONCACAF', coachHe: 'חאבייר אגירה', coachEn: 'Javier Aguirre',
    fifaRanking: 15, worldCupTitles: 0, bestResult: 'רבע גמר (1970, 1986)',
    group: 'A',
    squad: [
      { name: 'גיום אוסלי', number: 1, position: 'GK', club: 'קלאב אמריקה' },
      { name: 'חורחה סאנצ׳ס', number: 3, position: 'DEF', club: 'פורטו' },
      { name: 'שסאר מונטס', number: 4, position: 'DEF', club: 'פאצ׳וקה' },
      { name: 'חאביר גאיארדו', number: 8, position: 'MID', club: 'ריאל סוסיאדד' },
      { name: 'ירי מינה', number: 10, position: 'MID', club: 'פאצ׳וקה' },
      { name: 'חיריאן לוזאנו', number: 22, position: 'FWD', club: 'פאצ׳וקה', caps: 88, goals: 32 },
      { name: 'הנרי מרטין', number: 9, position: 'FWD', club: 'קלאב אמריקה' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2018, host: 'רוסיה', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: '16 האחרונות' },
      { year: 2010, host: 'דרום אפריקה', stage: '16 האחרונות' },
      { year: 1986, host: 'מקסיקו', stage: 'רבע גמר' },
    ],
  },
  {
    id: 'can', nameHe: 'קנדה', nameEn: 'Canada', flag: '🇨🇦',
    confederation: 'CONCACAF', coachHe: 'ג׳סי מרש', coachEn: 'Jesse Marsch',
    fifaRanking: 41, worldCupTitles: 0, bestResult: 'שלב הבתים (1986)',
    group: 'B',
    squad: [
      { name: 'מקסים קרפן', number: 1, position: 'GK', club: 'ניס' },
      { name: 'אלפונס דייבס', number: 3, position: 'DEF', club: 'באיירן מינכן', caps: 50, goals: 12 },
      { name: 'מילס מנאה', number: 5, position: 'DEF', club: 'ניוקאסל' },
      { name: 'אינה', number: 8, position: 'MID', club: 'בורוסיה דורטמונד' },
      { name: 'טבנן מור', number: 10, position: 'MID', club: 'שאלקה' },
      { name: 'ג׳ונתן דייוויד', number: 9, position: 'FWD', club: 'ליל', caps: 47, goals: 31 },
      { name: 'קייל לארין', number: 7, position: 'FWD', club: 'מאיורקה' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים', notes: 'חזרה ראשונה אחרי 36 שנה' },
      { year: 1986, host: 'מקסיקו', stage: 'שלב הבתים', notes: 'הופעת בכורה' },
    ],
  },
  {
    id: 'mar', nameHe: 'מרוקו', nameEn: 'Morocco', flag: '🇲🇦',
    confederation: 'CAF', coachHe: 'וואליד רחרחי', coachEn: 'Walid Regragui',
    fifaRanking: 14, worldCupTitles: 0, bestResult: 'חצי גמר (2022)',
    group: 'C',
    squad: [
      { name: 'יאסין בונו', number: 1, position: 'GK', club: 'אל הילאל' },
      { name: 'אכרף חכימי', number: 2, position: 'DEF', club: 'פריז סן ז׳רמן', caps: 75, goals: 11 },
      { name: 'נאיף אגיאד', number: 5, position: 'DEF', club: 'ואיד קאפיטאל' },
      { name: 'עזדין אוחלאל', number: 6, position: 'MID', club: 'נאפולי' },
      { name: 'סופיאן אמרבאת', number: 4, position: 'MID', club: 'אינטר מילאן' },
      { name: 'האקים זיאש', number: 7, position: 'FWD', club: 'גאלטסאראי', caps: 70, goals: 22 },
      { name: 'יוסף אן-נסירי', number: 9, position: 'FWD', club: 'ריאל ססיאדד' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'חצי גמר', notes: 'הישג היסטורי, הנבחרת האפריקנית הראשונה בחצי גמר' },
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'jpn', nameHe: 'יפן', nameEn: 'Japan', flag: '🇯🇵',
    confederation: 'AFC', coachHe: 'האג׳ימה מוריאסו', coachEn: 'Hajime Moriyasu',
    fifaRanking: 17, worldCupTitles: 0, bestResult: 'רבע גמר (2022)',
    group: 'H',
    squad: [
      { name: 'שוג׳י אוסוקו', number: 1, position: 'GK', club: 'ספורטינג ליסבון' },
      { name: 'ריוי יאמאנה', number: 2, position: 'DEF', club: 'ספורטינג' },
      { name: 'קו איטאקורה', number: 5, position: 'DEF', club: 'בורוסיה מ.גלדבך' },
      { name: 'ווטארו אנדו', number: 6, position: 'MID', club: 'ליברפול' },
      { name: 'שו קובאיאשי', number: 8, position: 'MID', club: 'חיתאצ׳י' },
      { name: 'קאורו מיטומה', number: 10, position: 'FWD', club: 'בריטון אנד הוב' },
      { name: 'טאקומי מינאמינו', number: 9, position: 'FWD', club: 'מונאקו' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'רבע גמר', notes: 'הגיעה לרבע גמר לאחר הפתעת גרמניה וספרד' },
      { year: 2018, host: 'רוסיה', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: '16 האחרונות' },
    ],
  },
  {
    id: 'sen', nameHe: 'סנגל', nameEn: 'Senegal', flag: '🇸🇳',
    confederation: 'CAF', coachHe: 'אליו סיסה', coachEn: 'Aliou Cissé',
    fifaRanking: 18, worldCupTitles: 0, bestResult: 'חצי גמר (2002)',
    group: 'B',
    squad: [
      { name: 'אדוארד מנדי', number: 1, position: 'GK', club: 'אל אהלי' },
      { name: 'כאלידו קוליבאלי', number: 3, position: 'DEF', club: 'אל הילאל' },
      { name: 'יוסוף סאבאלי', number: 2, position: 'DEF', club: 'ויאריל' },
      { name: 'פאפה גייה', number: 8, position: 'MID', club: 'אסטון וילה' },
      { name: 'אידריסה גייה', number: 6, position: 'MID', club: 'מרסיי' },
      { name: 'סאדיו מאנה', number: 10, position: 'FWD', club: 'אל נאסר', caps: 100, goals: 43 },
      { name: 'בולאייה דייא', number: 9, position: 'FWD', club: 'RC לאנס' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: '16 האחרונות' },
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים' },
      { year: 2002, host: 'יפן/קוריאה', stage: 'חצי גמר', notes: 'הישג ההיסטורי הגדול ביותר' },
    ],
  },
  {
    id: 'aus', nameHe: 'אוסטרליה', nameEn: 'Australia', flag: '🇦🇺',
    confederation: 'AFC', coachHe: 'טוני פופוביץ׳', coachEn: 'Tony Popovic',
    fifaRanking: 23, worldCupTitles: 0, bestResult: 'חצי גמר (2006)',
    group: 'G',
    squad: [
      { name: 'מאת׳יו ריאן', number: 1, position: 'GK', club: 'FC קופנהגן' },
      { name: 'ניי טיילס', number: 2, position: 'DEF', club: 'בייקנהאם' },
      { name: 'הארי סאוטרס', number: 6, position: 'DEF', club: 'שאלקה' },
      { name: 'אארון מוי', number: 10, position: 'MID', club: 'סלטיק' },
      { name: 'ריילי מקגרי', number: 7, position: 'MID', club: 'נורוויץ׳ סיטי' },
      { name: 'מיטשל דיוק', number: 9, position: 'FWD', club: 'אלביס' },
      { name: 'קיריאן שואנטל', number: 11, position: 'FWD', club: 'FC נאנט' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: 'חצי גמר' },
    ],
  },
  {
    id: 'cro', nameHe: 'קרואטיה', nameEn: 'Croatia', flag: '🇭🇷',
    confederation: 'UEFA', coachHe: 'זלטקו דאליץ׳', coachEn: 'Zlatko Dalić',
    fifaRanking: 10, worldCupTitles: 0, bestResult: 'גמר (2018)',
    group: 'G',
    squad: [
      { name: 'דומיניק ליוואקוביץ׳', number: 1, position: 'GK', club: 'פנרבחה' },
      { name: 'יוסיפ יוראנוביץ׳', number: 2, position: 'DEF', club: 'Celtic' },
      { name: 'ג׳וסקו גוארדיול', number: 5, position: 'DEF', club: 'מנצ׳סטר סיטי' },
      { name: 'לוקה מודריץ׳', number: 10, position: 'MID', club: 'ריאל מדריד', caps: 173, goals: 24 },
      { name: 'מארסלו ברוזוביץ׳', number: 11, position: 'MID', club: 'אל קדסייה' },
      { name: 'אנדריי קרמריץ׳', number: 9, position: 'FWD', club: 'TSG הופנהיים' },
      { name: 'בורנה סוסה', number: 23, position: 'DEF', club: 'AC מילאן' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'מקום שלישי' },
      { year: 2018, host: 'רוסיה', stage: 'גמר', notes: 'הישג הכדורגל הקרואטי' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: '16 האחרונות' },
    ],
  },
  {
    id: 'uru', nameHe: 'אורוגוואי', nameEn: 'Uruguay', flag: '🇺🇾',
    confederation: 'CONMEBOL', coachHe: 'מארסלו בילסה', coachEn: 'Marcelo Bielsa',
    fifaRanking: 16, worldCupTitles: 2, bestResult: 'אלוף (1930, 1950)',
    group: 'H',
    squad: [
      { name: 'סרג׳יו רוצ׳ה', number: 1, position: 'GK', club: 'ליגה דה קיטו' },
      { name: 'מתיאס אוליבירה', number: 3, position: 'DEF', club: 'וולנסיה' },
      { name: 'רונאלד אראוחו', number: 4, position: 'DEF', club: 'ברצלונה' },
      { name: 'ריימרו בנטנקורט', number: 8, position: 'MID', club: 'בוקה ג׳וניורס' },
      { name: 'פדרו פינס', number: 17, position: 'MID', club: 'מנצ׳סטר יונייטד' },
      { name: 'דרווין נונס', number: 11, position: 'FWD', club: 'ליברפול', caps: 40, goals: 18 },
      { name: 'פדרו ז׳יאמנץ', number: 9, position: 'FWD', club: 'ברצלונה' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2018, host: 'רוסיה', stage: 'רבע גמר' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: 'חצי גמר' },
      { year: 1950, host: 'ברזיל', stage: 'אלוף' },
    ],
  },
  {
    id: 'col', nameHe: 'קולומביה', nameEn: 'Colombia', flag: '🇨🇴',
    confederation: 'CONMEBOL', coachHe: 'נסטור לורנצו', coachEn: 'Néstor Lorenzo',
    fifaRanking: 8, worldCupTitles: 0, bestResult: 'רבע גמר (2014)',
    group: 'F',
    squad: [
      { name: 'קמילו ורגארה', number: 1, position: 'GK', club: 'ניוואל אולד בויז' },
      { name: 'דניאל מונוס', number: 2, position: 'DEF', club: 'ואלנסיה' },
      { name: 'קבינה רוסנה', number: 5, position: 'DEF', club: 'ריאל מדריד' },
      { name: 'ריצ׳ארד ריוס', number: 6, position: 'MID', club: 'פלמינגו' },
      { name: 'חואן קוואדראדו', number: 11, position: 'MID', club: 'אינטר מילאן' },
      { name: 'לואיס דיאז', number: 7, position: 'FWD', club: 'ליברפול', caps: 50, goals: 20 },
      { name: 'רדריגו פאלקאו', number: 9, position: 'FWD', club: 'בנפיקה' },
    ],
    tournamentHistory: [
      { year: 2018, host: 'רוסיה', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: 'רבע גמר' },
      { year: 1994, host: 'ארצות הברית', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'swi', nameHe: 'שווייץ', nameEn: 'Switzerland', flag: '🇨🇭',
    confederation: 'UEFA', coachHe: 'מוראט יאקין', coachEn: 'Murat Yakin',
    fifaRanking: 21, worldCupTitles: 0, bestResult: 'רבע גמר (1934, 1938, 1954)',
    group: 'A',
    squad: [
      { name: 'יאן זומר', number: 1, position: 'GK', club: 'אינטר מילאן' },
      { name: 'מנואל אקנג׳י', number: 5, position: 'DEF', club: 'מנצ׳סטר סיטי' },
      { name: 'זקי אמדובי', number: 8, position: 'MID', club: 'שלסי' },
      { name: 'גרנית שאקה', number: 10, position: 'MID', club: 'ברייטון', caps: 120, goals: 28 },
      { name: 'רמו אוקפי', number: 9, position: 'FWD', club: 'אורלאנדו סיטי' },
      { name: 'ברל אמבולו', number: 7, position: 'FWD', club: 'AS מונאקו' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'רבע גמר' },
      { year: 2018, host: 'רוסיה', stage: '16 האחרונות' },
      { year: 2014, host: 'ברזיל', stage: '16 האחרונות' },
      { year: 2010, host: 'דרום אפריקה', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'ecu', nameHe: 'אקוודור', nameEn: 'Ecuador', flag: '🇪🇨',
    confederation: 'CONMEBOL', coachHe: 'סבסטיאן בקה', coachEn: 'Sebastián Beccacece',
    fifaRanking: 42, worldCupTitles: 0, bestResult: '16 האחרונות (2006)',
    group: 'D',
    squad: [
      { name: 'הרנן גאלינדז', number: 1, position: 'GK', club: 'גרמינאל' },
      { name: 'אנגל מנה', number: 3, position: 'DEF', club: 'בנפיקה' },
      { name: 'פירסי טאפייה', number: 4, position: 'DEF', club: 'AS מונאקו' },
      { name: 'קרלוס גרופה', number: 8, position: 'MID', club: 'פיורנטינה' },
      { name: 'אנר ולנציה', number: 10, position: 'MID', club: 'ג׳וינטס' },
      { name: 'אדינסון ולנציה', number: 9, position: 'FWD', club: 'LDU קיטו', caps: 76, goals: 37 },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: '16 האחרונות' },
    ],
  },
  {
    id: 'kor', nameHe: 'קוריאה הדרומית', nameEn: 'South Korea', flag: '🇰🇷',
    confederation: 'AFC', coachHe: 'הונג מיי-בו', coachEn: 'Hong Myung-bo',
    fifaRanking: 22, worldCupTitles: 0, bestResult: 'חצי גמר (2002)',
    group: 'A',
    squad: [
      { name: 'קים סאונג-גיו', number: 1, position: 'GK', club: 'אולסאן' },
      { name: 'קים מין-ג׳אה', number: 3, position: 'DEF', club: 'באיירן מינכן' },
      { name: 'יון סאנג-הו', number: 13, position: 'DEF', club: 'גנבה' },
      { name: 'לי קאנג-ין', number: 10, position: 'MID', club: 'פריז סן ז׳רמן' },
      { name: 'הואנג הי-צ׳אן', number: 7, position: 'MID', club: 'RB לייפציג' },
      { name: 'סאן הו-מין', number: 9, position: 'FWD', club: 'טוטנהאם', caps: 115, goals: 36 },
      { name: 'צ׳ו גוק-סאנג', number: 11, position: 'FWD', club: 'בואנוס איירס' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: '16 האחרונות' },
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2002, host: 'יפן/קוריאה', stage: 'חצי גמר', notes: 'הפתעת הטורניר, מארחת משותפת' },
    ],
  },
  {
    id: 'par', nameHe: 'פרגוואי', nameEn: 'Paraguay', flag: '🇵🇾',
    confederation: 'CONMEBOL', coachHe: 'גוסטבו מוריניגו', coachEn: 'Gustavo Morínigo',
    fifaRanking: 61, worldCupTitles: 0, bestResult: 'רבע גמר (1954)',
    group: 'D',
    squad: [
      { name: 'ג׳ספר קייה', number: 1, position: 'GK', club: 'אסטון ויגן' },
      { name: 'גוסטבו גומז', number: 5, position: 'DEF', club: 'פלמסי' },
      { name: 'ג׳וני ווייבו', number: 8, position: 'MID', club: 'אינטר מילאן' },
      { name: 'מיגל אלמירון', number: 10, position: 'MID', club: 'אטלנטה יונייטד', caps: 65, goals: 13 },
      { name: 'הוסי מולדוואנו', number: 7, position: 'FWD', club: 'פנינסולרס' },
      { name: 'רנה ריוס', number: 9, position: 'FWD', club: 'אוליבנסה' },
    ],
    tournamentHistory: [
      { year: 2010, host: 'דרום אפריקה', stage: 'רבע גמר' },
      { year: 2006, host: 'גרמניה', stage: 'שלב הבתים' },
      { year: 2002, host: 'יפן/קוריאה', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'alg', nameHe: 'אלג׳יריה', nameEn: 'Algeria', flag: '🇩🇿',
    confederation: 'CAF', coachHe: 'ולד ריד', coachEn: 'Walid Regragui',
    fifaRanking: 50, worldCupTitles: 0, bestResult: '16 האחרונות (2014)',
    group: 'E',
    squad: [
      { name: 'ראיס עמיגש', number: 1, position: 'GK', club: 'לאנס' },
      { name: 'ראמי בנסבאיני', number: 3, position: 'DEF', club: 'פלאמינגהם' },
      { name: 'יאסין מרז', number: 4, position: 'DEF', club: 'ג׳לאר' },
      { name: 'ניסים סלאם', number: 8, position: 'MID', club: 'FC לורנט' },
      { name: 'ריאד מהרז', number: 10, position: 'FWD', club: 'אל אהלי', caps: 88, goals: 31 },
      { name: 'ישין אוניס', number: 9, position: 'FWD', club: 'MC אלג׳יר' },
    ],
    tournamentHistory: [
      { year: 2014, host: 'ברזיל', stage: '16 האחרונות' },
      { year: 2010, host: 'דרום אפריקה', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'qat', nameHe: 'קטאר', nameEn: 'Qatar', flag: '🇶🇦',
    confederation: 'AFC', coachHe: 'מארקוס פרנאנדז', coachEn: 'Marcelo García',
    fifaRanking: 35, worldCupTitles: 0, bestResult: 'שלב הבתים (2022)',
    group: 'B',
    squad: [
      { name: 'משעל ברשם', number: 1, position: 'GK', club: 'אל סד' },
      { name: 'פדרו מיגל', number: 2, position: 'DEF', club: 'אל דוחייל' },
      { name: 'בוואלאם', number: 5, position: 'DEF', club: 'אל סד' },
      { name: 'עיסא עיסא', number: 8, position: 'MID', club: 'אל סד' },
      { name: 'חסן אל חיידוס', number: 10, position: 'MID', club: 'אל רייאן', caps: 90, goals: 17 },
      { name: 'אלמועז עלי', number: 9, position: 'FWD', club: 'אל דוחייל', caps: 72, goals: 42 },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים', notes: 'הנבחרת המארחת, יצאה בשלב הבתים' },
    ],
  },
  {
    id: 'rsa', nameHe: 'דרום אפריקה', nameEn: 'South Africa', flag: '🇿🇦',
    confederation: 'CAF', coachHe: 'הוגו ברוס', coachEn: 'Hugo Broos',
    fifaRanking: 60, worldCupTitles: 0, bestResult: '16 האחרונות (2002)',
    group: 'A',
    squad: [
      { name: 'רון גורדון', number: 1, position: 'GK', club: 'מיראנדלה' },
      { name: 'נקוסינאטי מדוולה', number: 2, position: 'DEF', club: 'קאלוספה' },
      { name: 'גרנט קקרוט', number: 5, position: 'DEF', club: 'ספרינגבוקס' },
      { name: 'סטואן בורנס', number: 8, position: 'MID', club: 'פרטיזן' },
      { name: 'פרסי טאו', number: 10, position: 'FWD', club: 'אל אהלי', caps: 65, goals: 16 },
      { name: 'ריאן מולר', number: 9, position: 'FWD', club: 'קייפ טאון' },
    ],
    tournamentHistory: [
      { year: 2010, host: 'דרום אפריקה', stage: 'שלב הבתים', notes: 'הנבחרת המארחת' },
      { year: 2002, host: 'יפן/קוריאה', stage: '16 האחרונות' },
      { year: 1998, host: 'צרפת', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'nzl', nameHe: 'ניו זילנד', nameEn: 'New Zealand', flag: '🇳🇿',
    confederation: 'OFC', coachHe: 'דסיפ ריסבאי', coachEn: 'Darren Bazeley',
    fifaRanking: 95, worldCupTitles: 0, bestResult: 'שלב הבתים',
    group: 'F',
    squad: [
      { name: 'מייקל בקנהאם', number: 1, position: 'GK', club: 'הוורד' },
      { name: 'לוגאן ג׳פרי', number: 2, position: 'DEF', club: 'ג׳ורנאל' },
      { name: 'ביל טאנשי', number: 5, position: 'DEF', club: 'הוורד' },
      { name: 'ג׳ן סיגנאוס', number: 8, position: 'MID', club: 'ווסטון' },
      { name: 'אנדרה דה אנחס', number: 10, position: 'MID', club: 'יגאובה' },
      { name: 'כריס וד', number: 9, position: 'FWD', club: 'ניוקאסל', caps: 28, goals: 9 },
    ],
    tournamentHistory: [
      { year: 2010, host: 'דרום אפריקה', stage: 'שלב הבתים', notes: 'יצאו ללא הפסד (3 תיקו)' },
    ],
  },

  /* ─── UEFA – additional 7 ─── */
  {
    id: 'nor', nameHe: 'נורווגיה', nameEn: 'Norway', flag: '🇳🇴',
    confederation: 'UEFA', coachHe: 'ষ্টוֹলֵה סולבאקן', coachEn: 'Ståle Solbakken',
    fifaRanking: 14, worldCupTitles: 0, bestResult: 'שלב הבתים (1994, 1998)',
    squad: [
      { name: 'ארלינג הולאנד', number: 9, position: 'FWD', club: 'מנצ׳סטר סיטי', caps: 40, goals: 33 },
      { name: 'מרטין אודגור', number: 10, position: 'MID', club: 'ארסנל', caps: 75, goals: 24 },
      { name: 'אלכסנדר סורלוט', number: 22, position: 'FWD', club: 'אטלטיקו מדריד' },
      { name: 'סנדר בורגה', number: 6, position: 'MID', club: 'ברנטפורד' },
      { name: 'מאט טורסטבדט', number: 1, position: 'GK', club: 'ברייטון' },
      { name: 'אנדריאס קריסטנסן', number: 5, position: 'DEF', club: 'ניוקאסל' },
      { name: 'פטריק ברג', number: 8, position: 'MID', club: 'אל קדסייה' },
      { name: 'מוהמד אואינה', number: 7, position: 'FWD', club: 'AS מונאקו' },
      { name: 'פרדריק אאורסן', number: 11, position: 'FWD', club: 'Bayer Leverkusen' },
    ],
    tournamentHistory: [
      { year: 1998, host: 'צרפת', stage: 'שלב הבתים', notes: 'ניצחו ברזיל בשלב הבתים' },
      { year: 1994, host: 'ארצות הברית', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'aut', nameHe: 'אוסטריה', nameEn: 'Austria', flag: '🇦🇹',
    confederation: 'UEFA', coachHe: 'ראלף רנגניק', coachEn: 'Ralf Rangnick',
    fifaRanking: 25, worldCupTitles: 0, bestResult: 'מקום שלישי (1954)',
    squad: [
      { name: 'פטריק פנץ', number: 1, position: 'GK', club: 'ריאל סוסיאדד' },
      { name: 'מארסל זאביצר', number: 11, position: 'MID', club: 'מנצ׳סטר יונייטד', caps: 75, goals: 19 },
      { name: 'מיכאל גרגוריטש', number: 9, position: 'FWD', club: 'SC פריבורג' },
      { name: 'כריסטוף בוממגרטנר', number: 7, position: 'FWD', club: 'RB לייפציג' },
      { name: 'קונרד לאמר', number: 18, position: 'MID', club: 'RB לייפציג' },
      { name: 'פיליפ מוודר', number: 2, position: 'DEF', club: 'בורוסיה דורטמונד' },
      { name: 'קווין דנסו', number: 5, position: 'DEF', club: 'ליל' },
      { name: 'מרקוס אורנצ׳ר', number: 13, position: 'MID', club: 'וולפסבורג' },
    ],
    tournamentHistory: [
      { year: 1998, host: 'צרפת', stage: 'שלב הבתים' },
      { year: 1990, host: 'איטליה', stage: 'שלב הבתים' },
      { year: 1954, host: 'שווייץ', stage: 'מקום שלישי' },
    ],
  },
  {
    id: 'sco', nameHe: 'סקוטלנד', nameEn: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    confederation: 'UEFA', coachHe: 'סטיב קלארק', coachEn: 'Steve Clarke',
    fifaRanking: 32, worldCupTitles: 0, bestResult: 'שלב הבתים',
    squad: [
      { name: 'אנגוס גן', number: 1, position: 'GK', club: 'ניוקאסל' },
      { name: 'אנדרו רוברטסון', number: 3, position: 'DEF', club: 'ליברפול', caps: 80, goals: 3 },
      { name: 'סקוט מקטומיני', number: 8, position: 'MID', club: 'נאפולי', caps: 60, goals: 18 },
      { name: 'קירן טיירני', number: 5, position: 'DEF', club: 'ריאל סוסיאדד' },
      { name: 'בילי גילמור', number: 4, position: 'MID', club: 'ברייטון' },
      { name: 'ג׳ון מקגין', number: 7, position: 'MID', club: 'אסטון וילה', caps: 65, goals: 17 },
      { name: 'לורנס שנקלנד', number: 9, position: 'FWD', club: 'הרטס' },
      { name: 'ריאן כריסטי', number: 11, position: 'FWD', club: 'Celtic' },
    ],
    tournamentHistory: [
      { year: 1998, host: 'צרפת', stage: 'שלב הבתים' },
      { year: 1990, host: 'איטליה', stage: 'שלב הבתים' },
      { year: 1978, host: 'ארגנטינה', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'swe', nameHe: 'שוודיה', nameEn: 'Sweden', flag: '🇸🇪',
    confederation: 'UEFA', coachHe: 'יון דל טומסון', coachEn: 'Jon Dahl Tomasson',
    fifaRanking: 26, worldCupTitles: 0, bestResult: 'גמר (1958)',
    squad: [
      { name: 'רובין אולסן', number: 1, position: 'GK', club: 'AS רומא' },
      { name: 'ויקטור לינדלוף', number: 5, position: 'DEF', club: 'מנצ׳סטר יונייטד' },
      { name: 'אמיל פורסבורג', number: 10, position: 'MID', club: 'RB לייפציג', caps: 95, goals: 33 },
      { name: 'דיאן קולושבסקי', number: 8, position: 'MID', club: 'טוטנהאם', caps: 60, goals: 13 },
      { name: 'אלכסנדר איסק', number: 9, position: 'FWD', club: 'ניוקאסל', caps: 40, goals: 20 },
      { name: 'אנתוני אלוהו', number: 11, position: 'FWD', club: 'RC לאנס' },
      { name: 'ויקטור אורלסן', number: 3, position: 'DEF', club: 'Brentford' },
      { name: 'מאטיאס סבנסון', number: 6, position: 'DEF', club: 'Mainz' },
    ],
    tournamentHistory: [
      { year: 2018, host: 'רוסיה', stage: 'רבע גמר' },
      { year: 2006, host: 'גרמניה', stage: '16 האחרונות' },
      { year: 1994, host: 'ארצות הברית', stage: 'מקום שלישי' },
      { year: 1958, host: 'שוודיה', stage: 'גמר', notes: 'הפסד לברזיל 2-5' },
    ],
  },
  {
    id: 'tur', nameHe: 'טורקיה', nameEn: 'Türkiye', flag: '🇹🇷',
    confederation: 'UEFA', coachHe: 'וינצ׳נצו מונטלה', coachEn: 'Vincenzo Montella',
    fifaRanking: 40, worldCupTitles: 0, bestResult: 'מקום שלישי (2002)',
    squad: [
      { name: 'מרט גונוק', number: 1, position: 'GK', club: 'בשיקטש' },
      { name: 'האקאן צ׳לחאנוגלו', number: 10, position: 'MID', club: 'אינטר מילאן', caps: 90, goals: 22 },
      { name: 'ארדה גולר', number: 14, position: 'FWD', club: 'ריאל מדריד', caps: 20, goals: 7 },
      { name: 'קרם אקטורקאוגלו', number: 11, position: 'FWD', club: 'בשיקטש', caps: 55, goals: 20 },
      { name: 'בארישאן יילמאז', number: 9, position: 'FWD', club: 'RC לאנס' },
      { name: 'זקי צ׳ליק', number: 2, position: 'DEF', club: 'רומא' },
      { name: 'פרדי קדיאוגלו', number: 3, position: 'DEF', club: 'פנרבחה' },
      { name: 'מרט מולדור', number: 8, position: 'MID', club: 'ליל' },
    ],
    tournamentHistory: [
      { year: 2002, host: 'יפן/קוריאה', stage: 'מקום שלישי', notes: 'ההישג הטורקי הגדול ביותר' },
      { year: 1954, host: 'שווייץ', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'bih', nameHe: 'בוסניה-הרצגובינה', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦',
    confederation: 'UEFA', coachHe: 'סרגיי ברברז', coachEn: 'Sergej Barbarez',
    fifaRanking: 55, worldCupTitles: 0, bestResult: 'שלב הבתים (2014)',
    squad: [
      { name: 'ניקולה ווקאליץ׳', number: 1, position: 'GK', club: 'FK Sarajevo' },
      { name: 'אדין ג׳קו', number: 9, position: 'FWD', club: 'פנרבחה', caps: 115, goals: 64 },
      { name: 'מירלם פיאניץ׳', number: 8, position: 'MID', club: 'בשיקטש', caps: 110, goals: 22 },
      { name: 'ספד קולאשינץ', number: 3, position: 'DEF', club: 'Besiktas' },
      { name: 'אלדין יכובוביץ׳', number: 6, position: 'MID', club: 'וולפסבורג' },
      { name: 'ג׳נן סובוטיץ׳', number: 5, position: 'DEF', club: 'Mainz' },
      { name: 'עמר ספיץ', number: 7, position: 'FWD', club: 'OGC Nice' },
    ],
    tournamentHistory: [
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים', notes: 'הופעת הבכורה במונדיאל' },
    ],
  },
  {
    id: 'cze', nameHe: 'צ׳כיה', nameEn: 'Czechia', flag: '🇨🇿',
    confederation: 'UEFA', coachHe: 'איבן האשק', coachEn: 'Ivan Hašek',
    fifaRanking: 35, worldCupTitles: 0, bestResult: 'גמר (1962, כצ׳כוסלובקיה)',
    squad: [
      { name: 'ג׳ירי סטאנק', number: 1, position: 'GK', club: 'ברייטון' },
      { name: 'פאטריק שיק', number: 9, position: 'FWD', club: 'Bayer Leverkusen', caps: 55, goals: 28 },
      { name: 'טומאש סוצ׳ק', number: 8, position: 'MID', club: 'ווסטהאם', caps: 70, goals: 14 },
      { name: 'ולדימיר קופל', number: 2, position: 'DEF', club: 'ווסטהאם' },
      { name: 'אנטנין בארק', number: 7, position: 'MID', club: 'ליברפול', caps: 48, goals: 9 },
      { name: 'אונדרז׳יי דודה', number: 10, position: 'MID', club: 'SC הרתא' },
      { name: 'טומאש צ׳בקה', number: 5, position: 'DEF', club: 'מנצ׳סטר יונייטד' },
    ],
    tournamentHistory: [
      { year: 2006, host: 'גרמניה', stage: 'שלב הבתים', notes: 'כרפובליקה הצ׳כית' },
      { year: 1990, host: 'איטליה', stage: 'רבע גמר', notes: 'כצ׳כוסלובקיה' },
      { year: 1962, host: 'צ׳ילה', stage: 'גמר', notes: 'כצ׳כוסלובקיה, הפסד לברזיל' },
    ],
  },

  /* ─── CONCACAF – additional 3 ─── */
  {
    id: 'pan', nameHe: 'פנמה', nameEn: 'Panama', flag: '🇵🇦',
    confederation: 'CONCACAF', coachHe: 'תומאס כריסטיאנסן', coachEn: 'Thomas Christiansen',
    fifaRanking: 75, worldCupTitles: 0, bestResult: 'שלב הבתים (2018)',
    squad: [
      { name: 'לואיס מניאה', number: 1, position: 'GK', club: 'CD Árabe Unido' },
      { name: 'עדלברטו קראסקיה', number: 5, position: 'MID', club: 'הוסטון דיינמו', caps: 65, goals: 8 },
      { name: 'רולנדו בלקבורן', number: 9, position: 'FWD', club: 'CD Guabira' },
      { name: 'ציציליו ווטרמן', number: 11, position: 'FWD', club: 'CD Tauro', caps: 40, goals: 18 },
      { name: 'ג׳וסה פנוגה', number: 7, position: 'FWD', club: 'Atlanta United' },
      { name: 'הרולד קולה', number: 3, position: 'DEF', club: 'Tauro' },
      { name: 'אניבל גודוי', number: 6, position: 'DEF', club: 'CD Tauro' },
    ],
    tournamentHistory: [
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים', notes: 'הופעת בכורה במונדיאל' },
    ],
  },
  {
    id: 'cur', nameHe: 'קוראסאו', nameEn: 'Curaçao', flag: '🇨🇼',
    confederation: 'CONCACAF', coachHe: 'רמקו ביקנטיני', coachEn: 'Remko Bicentini',
    fifaRanking: 85, worldCupTitles: 0, bestResult: 'הופעת בכורה (2026)',
    squad: [
      { name: 'לינו הולדר', number: 1, position: 'GK', club: 'Scheveningen' },
      { name: 'לנדרו בקונה', number: 5, position: 'DEF', club: 'מידלסבורו', caps: 45, goals: 4 },
      { name: 'ג׳ונינהו בקונה', number: 8, position: 'MID', club: 'Hibernian', caps: 40, goals: 7 },
      { name: 'רנג׳לו ינגה', number: 9, position: 'FWD', club: 'KAS Eupen' },
      { name: 'פרדריק צ׳יגבו', number: 11, position: 'FWD', club: 'Lommel' },
      { name: 'גאין לוקביר', number: 3, position: 'DEF', club: 'ADO Den Haag' },
    ],
    tournamentHistory: [
      { year: 2026, host: 'קנדה/מקסיקו/ארה"ב', stage: 'הופעת בכורה', notes: 'האומה הקטנה ביותר בהיסטוריית המונדיאל' },
    ],
  },
  {
    id: 'hai', nameHe: 'האיטי', nameEn: 'Haiti', flag: '🇭🇹',
    confederation: 'CONCACAF', coachHe: 'הנרי פנלוס', coachEn: 'Henry Fenelus',
    fifaRanking: 96, worldCupTitles: 0, bestResult: 'שלב הבתים (1974)',
    squad: [
      { name: 'ג׳יימס לין', number: 1, position: 'GK', club: 'Violette AC' },
      { name: 'דקנס נאזון', number: 9, position: 'FWD', club: 'FK Čukarički' },
      { name: 'קארבל אנדרסון', number: 11, position: 'FWD', club: 'Columbus Crew', caps: 30, goals: 8 },
      { name: 'דריק אטין', number: 8, position: 'MID', club: 'NY Red Bulls' },
      { name: 'ג׳ינסון ז׳ן', number: 3, position: 'DEF', club: 'Violette AC' },
      { name: 'גייוון ג׳ין', number: 7, position: 'FWD', club: 'Don Bosco' },
    ],
    tournamentHistory: [
      { year: 1974, host: 'מערב גרמניה', stage: 'שלב הבתים', notes: 'ארנסט ז׳אן-ז׳וזף קלע לרשת האיטלקים; חזרה אחרי 52 שנה' },
    ],
  },

  /* ─── CAF – additional 6 ─── */
  {
    id: 'tun', nameHe: 'תוניסיה', nameEn: 'Tunisia', flag: '🇹🇳',
    confederation: 'CAF', coachHe: 'ז׳לל קאדרי', coachEn: 'Jalel Kadri',
    fifaRanking: 34, worldCupTitles: 0, bestResult: 'שלב הבתים',
    squad: [
      { name: 'איאס חמי', number: 1, position: 'GK', club: 'ריאל בטיס' },
      { name: 'ואהבי ח׳אזרי', number: 10, position: 'FWD', club: 'Montpellier', caps: 90, goals: 25 },
      { name: 'אליס סחירי', number: 8, position: 'MID', club: 'קולן', caps: 65, goals: 5 },
      { name: 'אניס סלימאנא', number: 11, position: 'FWD', club: 'Stoke City' },
      { name: 'מונתסר טלבי', number: 9, position: 'FWD', club: 'אינטר מילאן' },
      { name: 'ויסאם בן ידר', number: 7, position: 'FWD', club: 'AS מונאקו', caps: 50, goals: 17 },
      { name: 'נאסר קדיודה', number: 3, position: 'DEF', club: 'ספורטינג ליסבון' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: 'שלב הבתים' },
      { year: 1978, host: 'ארגנטינה', stage: 'שלב הבתים', notes: 'הנבחרת האפריקנית הראשונה לנצח במונדיאל' },
    ],
  },
  {
    id: 'egy', nameHe: 'מצרים', nameEn: 'Egypt', flag: '🇪🇬',
    confederation: 'CAF', coachHe: 'חוסאם חסן', coachEn: 'Hossam Hassan',
    fifaRanking: 32, worldCupTitles: 0, bestResult: 'שלב הבתים',
    squad: [
      { name: 'מוחמד אבו גבל', number: 1, position: 'GK', club: 'גירונה' },
      { name: 'מוחמד סלאח', number: 10, position: 'FWD', club: 'ליברפול', caps: 100, goals: 58 },
      { name: 'עמר מרמוש', number: 11, position: 'FWD', club: 'מנצ׳סטר סיטי', caps: 35, goals: 15 },
      { name: 'מוסטפה מוחמד', number: 9, position: 'FWD', club: 'נאנטס', caps: 45, goals: 16 },
      { name: 'מוחמד אלנני', number: 4, position: 'DEF', club: 'ארסנל' },
      { name: 'אחמד ח׳ג׳זי', number: 5, position: 'DEF', club: 'West Brom' },
      { name: 'ג׳אד בשיר', number: 8, position: 'MID', club: 'Pyramids FC' },
      { name: 'אמר קמרי', number: 7, position: 'FWD', club: 'אל אהלי' },
    ],
    tournamentHistory: [
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים', notes: 'חזרה אחרי 28 שנה' },
      { year: 1990, host: 'איטליה', stage: 'שלב הבתים' },
      { year: 1934, host: 'איטליה', stage: 'שלב הבתים', notes: 'הופעת הבכורה הראשונה של אפריקה' },
    ],
  },
  {
    id: 'gha', nameHe: 'גאנה', nameEn: 'Ghana', flag: '🇬🇭',
    confederation: 'CAF', coachHe: 'אוטו אדו', coachEn: 'Otto Addo',
    fifaRanking: 61, worldCupTitles: 0, bestResult: 'רבע גמר (2010)',
    squad: [
      { name: 'לורנס אטי-זיגי', number: 1, position: 'GK', club: 'Mainz 05' },
      { name: 'תומאס פרטי', number: 6, position: 'MID', club: 'ארסנל', caps: 50, goals: 8 },
      { name: 'מוחמד קודוס', number: 11, position: 'FWD', club: 'ווסטהאם', caps: 30, goals: 12 },
      { name: 'ג׳ורדן איו', number: 10, position: 'FWD', club: 'קריסטל פאלאס', caps: 90, goals: 22 },
      { name: 'אנטוניו ריגלה', number: 9, position: 'FWD', club: 'Sturm Graz' },
      { name: 'קלמנס אנקראה-בונסו', number: 5, position: 'DEF', club: 'Celtic' },
      { name: 'דניאל אמארטי', number: 7, position: 'MID', club: 'ולנסיה' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: 'רבע גמר', notes: 'הנבחרת האפריקנית הקרובה ביותר לחצי גמר' },
      { year: 2006, host: 'גרמניה', stage: '16 האחרונות' },
    ],
  },
  {
    id: 'cod', nameHe: 'ד.ר. קונגו', nameEn: 'DR Congo', flag: '🇨🇩',
    confederation: 'CAF', coachHe: 'סבסטיאן דסאבר', coachEn: 'Sébastien Desabre',
    fifaRanking: 62, worldCupTitles: 0, bestResult: 'שלב הבתים (1974 כזאיר)',
    squad: [
      { name: 'ז׳ואאו מלוומבה', number: 1, position: 'GK', club: 'AS Vita Club' },
      { name: 'שנסל מבמבה', number: 5, position: 'DEF', club: 'Marseille', caps: 55, goals: 3 },
      { name: 'ארתור מאסאוו', number: 3, position: 'DEF', club: 'ווסטהאם' },
      { name: 'סדריק בקמבו', number: 9, position: 'FWD', club: 'Basaksehir', caps: 45, goals: 19 },
      { name: 'פייר קלוקנה', number: 10, position: 'MID', club: 'Club Brugge' },
      { name: 'ז׳ונתן אוקיטה', number: 7, position: 'FWD', club: 'RWDM' },
      { name: 'כריסטל מאבה-מאבא', number: 8, position: 'MID', club: 'Strasbourg' },
    ],
    tournamentHistory: [
      { year: 1974, host: 'מערב גרמניה', stage: 'שלב הבתים', notes: 'כזאיר; הנבחרת האפריקנית הראשונה' },
    ],
  },
  {
    id: 'civ', nameHe: 'חוף השנהב', nameEn: "Côte d'Ivoire", flag: '🇨🇮',
    confederation: 'CAF', coachHe: 'אמרס פה', coachEn: 'Emerse Faé',
    fifaRanking: 47, worldCupTitles: 0, bestResult: 'שלב הבתים',
    squad: [
      { name: 'ייאן קנן', number: 1, position: 'GK', club: 'AC מילאן' },
      { name: 'פרנק קסיה', number: 6, position: 'MID', club: 'אל קאדסיה', caps: 80, goals: 12 },
      { name: 'סימון אדינגרא', number: 11, position: 'FWD', club: 'ברייטון', caps: 25, goals: 9 },
      { name: 'סבסטיאן האלר', number: 9, position: 'FWD', club: 'Borussia Dortmund', caps: 45, goals: 23 },
      { name: 'ניקולא פגה', number: 7, position: 'FWD', club: 'OGC Nice', caps: 65, goals: 16 },
      { name: 'סרז׳ אוריה', number: 8, position: 'MID', club: 'ריאל מדריד', caps: 50, goals: 3 },
      { name: 'אריק באילי', number: 5, position: 'DEF', club: 'Besiktas' },
    ],
    tournamentHistory: [
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2010, host: 'דרום אפריקה', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: 'שלב הבתים', notes: 'הופעת בכורה עם דידייה דרוגבא' },
    ],
  },
  {
    id: 'cpv', nameHe: 'קייפ ורדה', nameEn: 'Cape Verde', flag: '🇨🇻',
    confederation: 'CAF', coachHe: 'פדרו ליטאו', coachEn: 'Pedro Leitão',
    fifaRanking: 56, worldCupTitles: 0, bestResult: 'הופעת בכורה (2026)',
    squad: [
      { name: 'ווסטר מרטינס', number: 1, position: 'GK', club: 'FC Arouca' },
      { name: 'ריאן מנדס', number: 11, position: 'FWD', club: 'PAOK', caps: 60, goals: 15 },
      { name: 'גארי רודריגס', number: 10, position: 'FWD', club: 'Olympiakos', caps: 55, goals: 20 },
      { name: 'סטופירה', number: 5, position: 'DEF', club: 'Deportivo' },
      { name: 'קנדי', number: 7, position: 'FWD', club: 'Vitória de Guimarães' },
      { name: 'ז׳יפרה', number: 8, position: 'MID', club: 'FC Metz' },
    ],
    tournamentHistory: [
      { year: 2026, host: 'קנדה/מקסיקו/ארה"ב', stage: 'הופעת בכורה', notes: 'לראשונה במונדיאל' },
    ],
  },

  /* ─── AFC – additional 5 ─── */
  {
    id: 'irn', nameHe: 'איראן', nameEn: 'Iran', flag: '🇮🇷',
    confederation: 'AFC', coachHe: 'עמיר גלנואי', coachEn: 'Amir Ghalenoei',
    fifaRanking: 21, worldCupTitles: 0, bestResult: 'שלב הבתים',
    squad: [
      { name: 'עלירזה ביראנוונד', number: 1, position: 'GK', club: 'Tractor' },
      { name: 'מהדי טארמי', number: 9, position: 'FWD', club: 'אינטר מילאן', caps: 75, goals: 43 },
      { name: 'סארדאר אזמון', number: 23, position: 'FWD', club: 'AS רומא', caps: 68, goals: 26 },
      { name: 'עלירזה ג׳אנבחש', number: 7, position: 'FWD', club: 'Feyenoord', caps: 70, goals: 19 },
      { name: 'מוחמד מוחמדי', number: 3, position: 'DEF', club: 'Persepolis' },
      { name: 'עז אידין שאל', number: 5, position: 'DEF', club: 'Nottm Forest' },
      { name: 'שג׳ע חלילזאדה', number: 8, position: 'MID', club: 'Persepolis' },
      { name: 'מוחמד קלבי', number: 10, position: 'MID', club: 'Eastleigh' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים' },
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים' },
      { year: 2014, host: 'ברזיל', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: 'שלב הבתים' },
    ],
  },
  {
    id: 'ksa', nameHe: 'ערב הסעודית', nameEn: 'Saudi Arabia', flag: '🇸🇦',
    confederation: 'AFC', coachHe: 'הרנאן קרספו', coachEn: 'Hernán Crespo',
    fifaRanking: 56, worldCupTitles: 0, bestResult: 'רבע גמר (1994)',
    squad: [
      { name: 'מוחמד אל-עואיס', number: 1, position: 'GK', club: 'Al Hilal' },
      { name: 'סאלח אל-שהרי', number: 9, position: 'FWD', club: 'Al Ittihad', caps: 55, goals: 24 },
      { name: 'מוחמד אל-דוסרי', number: 7, position: 'FWD', club: 'Al Hilal', caps: 70, goals: 31 },
      { name: 'עבדאלה אל-חמדן', number: 11, position: 'FWD', club: 'Al Hilal', caps: 30, goals: 12 },
      { name: 'מוחמד קנו', number: 5, position: 'DEF', club: 'Al Nassr' },
      { name: 'עלי אל-בולאיחי', number: 6, position: 'DEF', club: 'Al Hilal' },
      { name: 'סאמי אל-נג׳י', number: 8, position: 'MID', club: 'Al Qadsiah' },
    ],
    tournamentHistory: [
      { year: 2022, host: 'קטאר', stage: 'שלב הבתים', notes: 'ניצחו ארגנטינה 2-1 בהפתעה' },
      { year: 2018, host: 'רוסיה', stage: 'שלב הבתים' },
      { year: 2006, host: 'גרמניה', stage: 'שלב הבתים' },
      { year: 1994, host: 'ארצות הברית', stage: 'רבע גמר' },
    ],
  },
  {
    id: 'irq', nameHe: 'עיראק', nameEn: 'Iraq', flag: '🇮🇶',
    confederation: 'AFC', coachHe: 'חסוס קאסס', coachEn: 'Jesús Casas',
    fifaRanking: 62, worldCupTitles: 0, bestResult: 'שלב הבתים (1986)',
    squad: [
      { name: 'בשאר רשן', number: 1, position: 'GK', club: 'Zamalek' },
      { name: 'מוחנד עלי', number: 10, position: 'FWD', club: 'Al Zawraa', caps: 38, goals: 16 },
      { name: 'עיסא ח׳ליל', number: 9, position: 'FWD', club: 'Al Zawraa', caps: 45, goals: 14 },
      { name: 'אחמד יאסין', number: 8, position: 'MID', club: 'Basra SC' },
      { name: 'עלי עדנאן', number: 3, position: 'DEF', club: 'Al Quwa Al Jawiya' },
      { name: 'קסים מחמוד', number: 5, position: 'DEF', club: 'Al Zawraa' },
    ],
    tournamentHistory: [
      { year: 1986, host: 'מקסיקו', stage: 'שלב הבתים', notes: 'הופעה היחידה עד 2026, חזרה אחרי 40 שנה' },
    ],
  },
  {
    id: 'jor', nameHe: 'ירדן', nameEn: 'Jordan', flag: '🇯🇴',
    confederation: 'AFC', coachHe: 'ח׳אשם אל-שבול', coachEn: 'Hashem Al-Shboul',
    fifaRanking: 71, worldCupTitles: 0, bestResult: 'הופעת בכורה (2026)',
    squad: [
      { name: 'יאזן ניימאט', number: 1, position: 'GK', club: 'Al Wehdat' },
      { name: 'אחמד הייאל', number: 9, position: 'FWD', club: 'Al Faisaly', caps: 35, goals: 13 },
      { name: 'עמר ח׳ריבין', number: 10, position: 'MID', club: 'Naft Tehran' },
      { name: 'נאסר אל-מוחמד', number: 7, position: 'FWD', club: 'Al Wehdat' },
      { name: 'יאסין מרסי', number: 5, position: 'DEF', club: 'Al Ahli' },
      { name: 'מוחמד אבו-חרב', number: 3, position: 'DEF', club: 'Al Faisaly' },
    ],
    tournamentHistory: [
      { year: 2026, host: 'קנדה/מקסיקו/ארה"ב', stage: 'הופעת בכורה', notes: 'לראשונה בהיסטוריה' },
    ],
  },
  {
    id: 'uzb', nameHe: 'אוזבקיסטן', nameEn: 'Uzbekistan', flag: '🇺🇿',
    confederation: 'AFC', coachHe: 'ספצ׳קו קטאנץ', coachEn: 'Srecko Katanec',
    fifaRanking: 70, worldCupTitles: 0, bestResult: 'הופעת בכורה (2026)',
    squad: [
      { name: 'אוטבק יוסופוב', number: 1, position: 'GK', club: 'Pakhtakor' },
      { name: 'אלדור שומורודוב', number: 9, position: 'FWD', club: 'AS רומא', caps: 55, goals: 25 },
      { name: 'ג׳לאלידין מאשריפוב', number: 10, position: 'MID', club: 'CSKA Moscow', caps: 50, goals: 12 },
      { name: 'ח׳ורשיד טורסונוב', number: 7, position: 'FWD', club: 'Pakhtakor' },
      { name: 'אוטבק שוקורוב', number: 5, position: 'DEF', club: 'Pakhtakor' },
      { name: 'ירלן קוצ׳קרוב', number: 8, position: 'MID', club: 'Bunyodkor' },
    ],
    tournamentHistory: [
      { year: 2026, host: 'קנדה/מקסיקו/ארה"ב', stage: 'הופעת בכורה', notes: 'לראשונה בהיסטוריה' },
    ],
  },
];

export const fallbackPlayerStats: WorldCupPlayerStat[] = [
  { rank: 1, playerName: 'יעודכן עם פתיחת הטורניר', team: teams.tbd, goals: 0, assists: 0, shots: 0, minutes: 0 },
  { rank: 2, playerName: 'נתוני שערים בזמן אמת', team: teams.tbd, goals: 0, assists: 0, shots: 0, minutes: 0 },
  { rank: 3, playerName: 'סטטיסטיקות שחקנים', team: teams.tbd, goals: 0, assists: 0, shots: 0, minutes: 0 },
];
